---
tags:
  - interest_rates
  - monetary_policy
  - recession
  - term_premium
  - yield_curve
aliases:
  - Term Premium Update
  - Yield Curve Analysis
key_concepts:
  - Inverted yield curves
  - Monetary policy impact
  - Quantitative easing (QE)
  - Term premium measurement
  - Yield curve evolution
---

# Chapter 7 An Update of the Term Premium Calculation

# Introduction

Chapter 6 is simply a reproduction of the 2017 paper which introduced our model for the [Term Premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md). In 2019, we updated the results as yields fell to lower levels than ever before, and this chapter contains a further update where possible.' We were able to source data from a selection of different models to form a useful comparison.

# Evolution of Yield Curves

As explained in Chapter 6, the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) is difficult to measure and extract from the other factors that determine the level and shape of the interest rate yield curve. With [interest rates](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%202/Interest%20Rate%20Quotations.md) in many major economies dipping in and out of negative territory, even at longer-dated maturities, the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) can now be the dominant factor that determines whether the yield curve slope is positive or negative. Inverted yield curves have historically been a harbinger of recessions and economic problems, as they signal that [monetary policy](../../../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%209-%20Bailouts%20and%20Bank%20Failures/Articles/The%20Economist%20Regime%20Change.md) is restrictive ([short-term rates](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%208/Volatility%20and%20Convexity.md) set by the central bank are higher than the market's equilibrium rate), and thus embody a market view of an economic slowdown ahead. Thus, it becomes a matter of critical interest to be able to extract the 'true' yield curve, the actual market view on [future interest rate](../../../Clippings/Forward%20Rate.md), separate from the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md).

Figures 7.1 and 7.2 show the evolution of the USD and EUR yield curves, at quar. terly frequency, as a surface.

It is argued in Cohen et al. (2018), Li et al. (2017) and Swanson (2007) that the general lowering and flattening or even inversion of the yield curve as seen in Figures 7.1 and 7.2 is largely due to falling-term premia over the same period. Accordingly, studies (e.g. Haltom et al. [2018]) argue that curve inversions are no longer as valid a proxy for recessions as in the past, as the falling-[term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) (and thus the curve flattening) relates to factors other than recessions fears.

The [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) is a critical element in [monetary policy](../../../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%209-%20Bailouts%20and%20Bank%20Failures/Articles/The%20Economist%20Regime%20Change.md). For one, dissecting significant rate moves into changes in genuine rate [expectations](../../../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) and varying risk premia is crucial for determining the policy response. While [monetary policy](../../../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%209-%20Bailouts%20and%20Bank%20Failures/Articles/The%20Economist%20Regime%20Change.md) can directly address short-rate [expectations](../../../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) via rate cuts (and hikes), adjusting the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) is primarily done via QE.

![](bd292e144b5787824b42cd79059b7eaeff7299553681062fa458abe44e4596c8.jpg)
Figure 7.1: Evolution of EUR yield curve, various tenors, in $\%$ Source: Bloomberg

![](a9339027aebe3fc94ac6d0a965ef6dd2ab2e710d2aa51ffdcefc917cb7625842.jpg)
Figure 7.2: Evolution of UsD yield curve, various tenors, in $\%$ Source: Bloomberg

Various papers conclude that [monetary policy](../../../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%209-%20Bailouts%20and%20Bank%20Failures/Articles/The%20Economist%20Regime%20Change.md) can only impact long-term yields by modifying term premia (Bernanke et al. [2005], Crump et al. [2016], and Kopp and Williams [2018]). Policymakers would like to know the likely impact upon longerterm yields of the volume and maturity of [government debt](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Front%20Matter/Global%20Fixed%20Income%20Markets.md) they remove from the market via [quantitative easing](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Front%20Matter/Negative%20Rates%20and%20Qe%20in%20Europe%20and%20Japan.md).

Policymakers could also refrain from countering a change in yields driven by changes in the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) if it were deemed to be driven by factors outside its control, like the so-called savings glut (more savings chasing fewer investments in an ageing society), a general flight-to-safety or [hedging](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%205/Key%20Rates%20O1s%20Durations%20and%20Hedging.md) demand from ALM investors. The same holds true for a shift in the market's [risk assessment](../../../Financial%20Engineering/10.%20Other%20Topics%20in%20Quantitative%20Finance.md), which does not equate to unwarranted policy easing or tightening (note for example that regarding declining EUR [inflation](../../../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md) break-evens, the ECB frequently attributes these to a declining [inflation](../../../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md) risk premium, which does not warrant a policy response).

Investors would like to be able to capture the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) and compare risk/. reward across currencies and asset classes, while a robust [risk-free rate](../../../Financial%20Instruments/Black%20Scholes%20Derivation.md) is a key. input into equity (and other DCF) valuation models. Likewise, issuers could under-. stand which parts of their funding costs reflect their unique credit profile and which. are simply due to fluctuations in the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) (i.e. the fundamental [market price of risk](../../Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) demanded by investors)..

Accordingly, the lack of clarity about variations in the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) arising from various approaches to measuring it (i.e. model risk) makes the impact of rate cuts and non-standard measures even harder to predict than they would be otherwise.

Crucially, varying signals from different [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) models imply different. policy responses as well as relative value and valuation assessments. A good understanding of term premia values and their variation has seldom been more important than it is today.

# Term Premium Values Over Time

There have been a number of different attempts to calculate current and historical values of the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md). A literature review might discover perhaps 15 separate. methods, some of these subdivided into several variants. The data that they are based on is varied; yield curves through time are of course popular sources of [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) information, but so are [inflation](../../../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md), economic inputs, and surveys of market participants. What is surprising is not so much that they all give different results,. but that they all do tend to agree on overall shape and direction, to an extent. It is difficult to source live or even historical data for all of them, as many are not published in data form or updated, but for those which we could discover, we have graphed the results in Figure 7.3. Although most models in theory would give a [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) value as a function of tenor, in practice the 1Oy [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) is the most often calculated and published. Although it should be possible to generalise any model to any [currency](../../../Financial%20Instruments/Lecture%20Notes-%20Financial%20Instruments/Teaching%20Note%201-%20Forward%20Rates%20Agreement/Forwards%20and%20Futures%20Notes.md), in practice the US dollar tends to get most of the. attention.

![](24a558da7a27c0a819d6ee1a62a4f49a1f8f29a8b0d85b72028b0a9af006571c.jpg)
Figure 7.3: [Term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) results, 10y [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md), in $\%$ Source: Bloomberg, Commerzbank Research, San Francisco Federal Reserve, St. Louis Federal Reserve, BlS Quarterly Report Sep 2018

Overall, it is certainly true to say that there has been a decline in [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md). values over time. All show a peak and then decline at the start of the millennium, and all show a spike and decline after the 2o08 crisis. After that period, there is a brief recovery in 2014, followed by an overall downtrend until the present day..

# Term Premium Models; Similarities and Differences

As can be seen in Figure 7.3, we have six separate models that give [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) results for a period since 2001. We can categorise them by the data that they use as inputs, as well as the [pricing](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%207/Arbitrage%20Pricing%20of%20Derivatives.md) model and estimation technique to compute the [pricing](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%207/Arbitrage%20Pricing%20of%20Derivatives.md) factors they use to create the final [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) number. Note however that not all of the models are quite up to date, as not all data were available for the most recent time.

Overall, those that include only yield curve data (like ACM and Coba) tend to be. the most volatile and perhaps the most responsive, though anomalous curve behaviour can translate into noisy results. Those models that access broader data sources, like Hordahl-Tristani, tend to be less volatile and give smoother [returns](../../Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md)..

1. HT: Hordahl-Tristani (Hordahl and Tristani [2014]) - Input data is nominal and real (index-linked) yields, [inflation](../../../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md), survey data on future short-term [interest rates](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%202/Interest%20Rate%20Quotations.md) and future [inflation](../../../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md) rates, and a measure of economic slack (the [output gap](../../../International%20Finance/Economic%20Stabilization%20Notes/Topics%20in%20Fiscal%20and%20Monetary%20Policies%20and%20Stabilization-%20Empirical%20Issues.md)). The method uses a forward-looking Phillips curve model. ACM: Adrian, Crump and Moench (Adrian et al. [2013]) - Uses only yield curve data as inputs. Uses an affine [term structure](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%209/The%20Vasicek%20Model.md) model with [principal components](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%206/Principal%20Component%20Analysis.md) of bond yields as [pricing](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%207/Arbitrage%20Pricing%20of%20Derivatives.md) factors that are assumed to follow an vector autore-. gressive (VAR) process.

3.KW: Kim-Wright (Kim and Wright [2005]) - Similar to ACM, but KW incorporates Blue Chip surveys of professional forecasters' short-rate [expectations](../../../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) in the data set used to estimate the model. SPF: Survey of Professional Forecasters - This is a model-free estimate, calculated as the 10y yield minus the corresponding 10y average [short rate](../../../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/An%20Overview%20of%20the%20Vasicek%20Short%20Rate%20Model.md) expectation, as reported once a year by the Survey of Professional Forecasters (SPF). CR: Christensen and Rudebusch (Christensen and Rudebusch [2019]) - This model uses [inflation-indexed](Chinese%20Financial%20System.md) [US Treasuries](../../../Credit%20Markets/Credit%20Market%20PSETS/Credit%20Market%20Homework%201.md) (TIPs) and a dynamic [term structure](../../Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%209/The%20Vasicek%20Model.md) model. Coba: Commerzbank Research (see James et al. [2016] and Chapter 6) - This model takes swap rates as inputs but uniquely includes historical yields as well as current yields. The method assumes that forward rates, in the absence of a [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md), would be on average a good predictor of the future, and takes this forward error' to be a forward curve of the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) [spot curve](../../../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/Teaching%20Note%204%20Interest%20Rate%20Derivatives.md).

It is useful to look at the volatilities of the different models to see how their construction and methodology affect their output. In Table 7.1, we see that the models that incorporate econometric data like HT have lower volatility, whereas those with only yield curve data like ACM and Coba are higher. Note that the SPF data is annual, so this figure is only from linear interpolation and is thus bound to be lower.

Table 7.1: Volatilities of [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) models, standard deviation of monthly changes in $\%$


<html><body><table><tr><td>Model</td><td>HT</td><td>ACM</td><td>KW</td><td>SPF</td><td>CR</td><td>Coba</td></tr><tr><td>St.Dev.</td><td>0.47%</td><td>1.05%</td><td>0.64%</td><td>0.53%</td><td>1.08%</td><td>1.00%</td></tr></table></body></html>

Source: Commerzbank Research

# Aggregating Model Results

Is there any utility in attempting to pin down the sources of the differences in levels that these models give? Can we approach a 'true' [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) any more closely? There are some useful discussion papers on this topic (for a good summary, see. Cohen et al. [2018]), but it seems that there is no consensus as to the 'best' one out there. All [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) estimates are model-dependent and are subject to parameter uncertainty. Some are not 'up to date' until a while after their initial publication, and values will change due to macro data revisions and delays. For example, in the case of the Coba model, it is not 'accurate' until there is a year of back-data included. (i.e. the initial [forwards](../../Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Forwards%20and%20Futures.md) are realised and can be 'evaluated'), though before that time, the model gives approximate results.

Recent problems with econometric models have arisen where they need adjustment to cope with the relatively new phenomenon of rates being bounded at zero or slightly below it. Thus, we do not attempt to pick and choose, but it is interesting to look at an aggregation of available data and the degree of model variation as a function of time.

In Figure 7.4, we graph a simple average of the available models (the black line). For each month, we then calculate a standard deviation of the cross section of the model results (so, seven data points for each standard deviation calculation). Then we use this to put 1 standard deviation band around the monthly results. The bands provide an indication of the spread of model values at each point in time; wider bands indicate a greater degree of model 'disagreement'. Finally, the shaded grey area is the actual value of this standard deviation.

Unsurprisingly, there is significant noise around the 2008 [financial crisis](../../../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%209-%20Bailouts%20and%20Bank%20Failures/Squam%20Lake%20Group%20Letter.md). After this, the models tend to agree more and more closely up to around 2016, with more divergence thereafter as yield curves entered often uncharted territory. What is notable, however, is the correlation between the level of standard deviation and rises in the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md). The models seem to diverge more on the way up and achieve a degree of consensus on the way down.

It is clear that we are on a downward slope. Current values of the aggregated. [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) are headed for a record low, with models lining up to agree. Is the current decline to record lows in long-term yields due to (1) caution about the future and insurance-buying behaviour, or (2) is it just that the market has decided that policy normalisation is a long way off? If (1), then the [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) would be the dominant driver, but (2) would indicate that rate [expectations](../../../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) are responsible..

![](0969f20af2a9e1bfa2fb7c05a0c50592b63896825e738ad68ac020939e882e4e.jpg)
Figure 7.4: Average 10y USD [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md), [term premium](../../../Contemporary%20Financial%20Intermediation%20Notes/Table%20of%20Contents.md) averaged over models, with standard deviation bands. Source: Bloomberg, Commerzbank Research, San Francisco Federal Reserve, St. Louis Federal Reserve, BIS Quarterly Report Sep 2018