---
title: An Asset Allocation Primer
cssclasses:
  - academia
  - finance
tags:
  - asset_allocation
  - asset_classes
  - diversification
  - investment_strategy
  - portfolio_management
  - risk_budgeting
  - efficient_frontier
  - human_capital
  - portfolio_construction
  - risk_management
  - institutional_investing
aliases:
  - Asset Allocation
  - Investment Primer
  - Portfolio Construction Basics
  - Strategic Asset Allocation
  - Asset Allocation Fundamentals
key_concepts:
  - active versus systematic risk
  - asset allocation methodology
  - diversification benefits
  - purchasing power transportation
  - two-step allocation approach
  - market-weighted portfolio construction
  - conditional asset allocation strategies
  - efficient frontier optimization
  - asset location tax strategies
  - liquidity premium capture
  - risk budgeting techniques
  - strategic versus tactical allocation
  - lifestyle and lifecycle investment approaches
  - multi-asset portfolio management
  - risk factor decomposition
---

# An Asset Allocation Primer

Brian J. Jacobsen, Ph.D., CFA, CFP®  

Wells Fargo Funds Management, LLC February 05, 2010  

The views expressed are as of February 05, 2010 and are those of Dr. Brian Jacobsen, CFA, CFP® and not those of Wells Fargo Funds Management, LLC. The views are subject to change at any time in response to changing circumstances in the market and are not intended to predict or guarantee the future performance of any individual security, market sector or the markets generally.  

Wells Fargo Funds Management, LLC, is a registered investment advisor and a wholly owned subsidiary of Wells Fargo & Company.  

NOT FDIC INSURED-NO BANK GUARANTEE-MAY LOSE VALUE  

# What is Asset Allocation?

Asset allocation refers to what proportion of a portfolio should be placed in the relevant asset classes. An asset allocation strategy is the set of decision rules that enables the "asset manager" to determine an asset allocation at a particular point in time.

Even though some have defined asset allocation as building a diversified portfolio utilizing different asset classes or investment categories, in fact, diversification and asset allocation are related, but not identical. An asset allocation could involve making a concentrated investment. Whether to make a diversified investment is a follow-up consideration to the asset allocation decision.

One way of thinking of an asset allocation strategy is to analogize it to a transportation problem: how do you help transport today's purchasing power to future purchasing power? A client could have all of his wealth in cash, which is purchasing power in the present. However, a client likely wants to accomplish future goals—whether it is future consumption, gifting, or some other objective—with the present purchasing power, which may include planned future savings. An asset allocation strategy is a plan for how to transport today's purchasing power to the future by using various investments.

Typically, investors approach asset allocation in two steps: first, determine the optimal allocation to each broad asset class, and second, select active and passive managers to implement the allocation within each asset class. Using this two-step approach, however, can inadvertently add systematic risk to a portfolio because an active manager's investment strategy may increase or decrease systematic risk depending upon market conditions. Many advisors use tracking error to measure a manager's active risk, but tracking error can vary depending upon whether markets are rising or falling. For example, a common stock fund benchmarked against the Russell 2500 analyzed for this paper has a daily tracking error of $0.36\%$ in falling markets (i.e., when the Russell 2500 had a negative daily return), but a daily tracking error of $0.27\%$ in rising markets. If active risk (risk added by an active manager) were separable from systematic risk (represented by broad exposure to a benchmark), then the tracking error in rising and falling markets would be nearly identical.

In Adam Smith's An Inquiry into the Nature and Causes of the Wealth of Nations (1776), he wrote about the division of labor. Today, we would think of this as specialization—individuals should perform those activities in which they have a comparative advantage. In the asset management business, portfolio managers tend to specialize in picking securities within a particular asset class. A financial advisor then specializes in combining those asset classes to accomplish a client's unique goals. This framework of specialization can also benefit retail customers who have limited knowledge of investment opportunities and must pay higher costs than asset managers to access the financial markets.

There are numerous benefits of using mutual funds to implement an asset allocation strategy, including professional management, diversification (across securities and within an investment style), economies of scale, and flexibility (e.g., the easy exchange of fund shares). Investors can obtain manager diversification along with security diversification by using multiple mutual funds to represent a particular asset class.

Brian Jacobsen, Wells Fargo Funds Management, LLC 3

# What Are Asset Classes?

It is often useful to group similar investments together into asset classes. This begs the question, though, of what makes different investments similar? Categories can be useful, but are not perfect. A danger inherent in [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) is assuming that asset categories or asset classifications create homogeneous groups of securities. Assuming securities are more correlated (or subject to the same risks) within a category than between categories can be faulty. Another problem is what Ennis (2009) refers to as "category proliferation and ambiguity." It is always possible to further differentiate between categories, and some securities seem to be so unique that they defy easy categorization, going into an "alternative" category.

All securities are imperfect substitutes for all others, but some are better substitutes than others while others are worse. One idea that has caught on in the [investment](.md) community is that of style boxes, in which equity securities are categorized as large, mid, or small, and then value, core, or growth stocks. Different index providers provide their own categorization schemes. However, the whole notion of style boxes may be misused. The original justification for style and size categories was presented in [Fama and French](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Empirical%20Factors.md) (1992), but the [Fama and French](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Empirical%20Factors.md) framework would tell everyone to hold small cap value stocks and no one to hold large cap growth stocks. Although style box categories are useful for identifying a few broad common [risk factors](../Financial%20Instruments/Assignments/PSET%206-%20Financial%20Instruments.md), many have misinterpreted them as silos across which investors should spread their money.

Likewise, many use style boxes or asset classes for diversification. Remember, with [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md), you can choose to allocate assets according to either a diversified or a concentrated method. If you hold [fixed income](../Fixed%20Income%20Asset%20Pricing/Lecture%20Notes%20Bonds,%20%20Preferred%20Stock,%20%20and%20Structured%20Products.md) and equities, that is not necessarily a [diversified portfolio](../Financial%20Engineering/Derivatives/Part%20I%20-%20Forwards%20and%20Futures/Chapter%205%20-%20Index%20Futures.md), especially if it consists of the [debt and equity](../Financial%20Markets%20and%20Institutions/I-%20Introduction%20to%20Financial%20Markets%20and%20Intermediation/I-%20Introduction%20to%20Financial%20Markets%20and%20Intermediation/Class%20Note%201-%20Borrower-Lender%20conflicts%20and%20implied%20agency%20problems.md) of a single issuer. The idea of [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) is not to "check-the-boxes," but to identify those risks you are willing to take and to construct a [portfolio](.md) consistent with your views.  

# Systematic Risk and Active Risk  

One way to think of asset classes is through a style/size framework. However, I think a better way is to think of exposures to systematic and active risks. The risk of a security can be described by its exposure to systematic factors, the volatility of those systematic factors, and the residual (or active) risk. An investor can get passive exposure to systematic risks with little effort or cost (e.g., through a passive index fund). Active risk comes from ongoing decisions made in managing and revising a [portfolio](.md). The allocation decision is then a reflection of how much systematic and active risk the investor wants in the [portfolio](.md).8  

Systematic risk exposure can be defined in a number of ways. Generally, it is anything that indiscriminately impacts a large part of the market. For example, sector exposure can be thought of as a risk exposure. All companies that operate within a particular sector, sub-sector, industry, or subindustry are subject to common [risk factors](../Financial%20Instruments/Assignments/PSET%206-%20Financial%20Instruments.md). Regulatory and demographic changes are two examples of [risk factors](../Financial%20Instruments/Assignments/PSET%206-%20Financial%20Instruments.md) that typically impact an entire industry instead of just a single security.  

Another systematic risk exposure can be the type of security. For example, all [debt securities](../Fixed%20Income%20Asset%20Pricing/Analysis%20of%20Fixed%20Income%20Securities.md) are. subject to factors that equities are not directly exposed to, such as taxation and bankruptcy law changes. There are also factors related to [interest rates](../Financial%20Markets/Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%202/Interest%20Rate%20Quotations.md) that have a more immediate impact on debt. than on equities.  

The most common starting point for [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) is determining how much exposure you want to the systematic risks. Anson (2004) refers to these exposures as the "beta drivers" of a [portfolio](.md). In the longrun, this decision will tend to dominate the contribution to total [portfolio](.md) return. After determining the systematic risk exposure, investors then need to decide whether to add active risk to the [portfolio](.md) through [portfolio](.md) managers. Active managers would be what Anson (2004) refers to as the "alpha drivers" of a [portfolio](.md).  

Investors can be thought of as having a risk budget, which is a summary of the risks the investor is.   
willing and able to bear. This risk budget then needs to be allocated across systematic factors. Bearing.   
systematic risk is rewarded with an expected market-wide risk premium (i.e., a return in excess of a risk-.   
free alternative). Active [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md), on the other hand, depend on the skill of particular managers..   
Investors who have concerns about managers' abilities to generate consistently positive active [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) will tend to be less tolerant of bearing active risk..  

# What is a "normal" allocation?  

# Defining the investment universe  

Not every [investment](.md) will be available or appropriate for every client. Some may want to invest in artwork or classic automobiles, but most investors will likely be constrained to investing in assets that are available through their advisor. Moreover, those assets that are available might not be appropriate; advisors must construct a screen of some sort to filter out what is or is not appropriate. A good initial screen is based on the risk tolerance of an investor. For example, conservative investors may prefer to invest in securities that generate predictable income. Indeed, for conservative investors, predictability may trump diversification.  

Securities have different characteristics in terms of the predictability of cash flows. As Bodie (2003) points out, investors' welfare depends not only on their end-of-period wealth but also on the consumption of goods and leisure over their lifetimes. Additionally, [habit formation](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%208%20-%20Consumption-Based%20Asset%20Pricing/CCAPM%20with%20Alternative%20Preferences.md) can give rise to a demand for assurances against a decline in total income, which includes both labor income and [investment](.md) income. Thus a so-called conservative investor might actually prefer a more concentrated [portfolio](.md) over a [diversified portfolio](../Financial%20Engineering/Derivatives/Part%20I%20-%20Forwards%20and%20Futures/Chapter%205%20-%20Index%20Futures.md), if it results in more predictable cash flows.  

The typical way to deal with equity risk aversion is to increase cash and bond holdings relative to equities.' An alternative way to think of handling client risk aversion is that conservative investors will want more self-liquidating assets than aggressive investors. If you view any security as a bundle of claims to both predictable and unpredictable cash flows, self-liquidating securities are those which have a predetermined structure over which they are paid off. For example, a preferred stock has a  

Brian Jacobsen, Wells Fargo Funds Management, LLC 5 predetermined [cash flow](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20I%20RELATIVE%20VALUE%20BUILDING%20BLOCKS/Chapter%201%20-%20Purpose%20and%20Structure%20of%20Financial%20Markets/Preview%20of%20the%20Book.md) stream (albeit subject to some uncertainty) whereas a common stock does not. However, a share of preferred stock is not as self-liquidating as a fixed-rate coupon bond because the preferred stock never matures. A fixed-rate coupon bond has a pre-determined maturity date. In the absence of default, an investor can hold onto the bond until maturity and receive the contractual cash flows. The cash flows only become uncertain if the investor wants to liquidate the security before the maturity date. However, that uncertainty is pre-determined in [duration](../Financial%20Markets/Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%205/Key%20Rates%20O1s%20Durations%20and%20Hedging.md)-as the bond approaches maturity, its market price will approach its par value, regardless of the level of [interest rates](../Financial%20Markets/Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%202/Interest%20Rate%20Quotations.md); at a point, the [investment](.md) matures (i.e., it self-liquidates).  

[Inflation](../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md) risk obviously plays a role here too since fixed-rate securities are fixed in nominal terms, not real ([inflation](../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md) adjusted) terms. Thus, a variable-rate or adjustable-rate security may be more selfliquidating than a fixed-coupon bond. The consummate self-liquidating security is a Treasury InflationProtected Security (TIPs), which is only subject to the [default risk](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20I%20RELATIVE%20VALUE%20BUILDING%20BLOCKS/Chapter%207%20-%20Default%20Risk%20and%20Credit%20Derivatives/Default%20Risk%20and%20Credit%20Derivatives%20183.md) of the government. At maturity, a TIPS pays ff the [inflation](../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md)-adjusted principal or the face value, whichever is greater.10  

Conservative investors who have a need for predictable cash flows will tend to look for investments that generate income, such as preferred stock, bonds, real estate [investment](.md) trusts, or master limited. partnerships. Investors who do not place such a high value on predictable cash flows will likely limit. their [investment](.md) universe to non-income generating securities such as common stock, [commodities](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20I%20RELATIVE%20VALUE%20BUILDING%20BLOCKS/Chapter%203%20-%20Futures%20Markets/Futures%20Not%20Subject%20to%20Cash-And-Carry.md), or. currencies. An interesting implication of this approach is that investors interested only in total return will include all investable assets in their [investment](.md) universe. Investors with a need for cash flows, or with a higher tolerance for risk, will have a more concentrated [portfolio](.md), eliminating some assets from consideration.  

# Historical Averages: Unconditional Allocations  

One of the most well-documented, and perhaps most controversial, methods of determining an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) is through Modern [Portfolio Theory](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20III%20THE%20PLAYERS/Chapter%2011%20-%20Individual%20Investors-A%20Survey%20of%20Modern%20Investment%20Theory/A%20Brief%20History%20of%20Investment%20Thought.md) (Mpt).11 Most criticisms of the theory are not valid. critiques of the theory, but rather, criticisms of a particular application of the theory..  

The concept behind MPT is simple: If securities behave like random variables, then, based on the assumed [probability distributions](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) of the securities, an investor must examine the combinations of. securities to minimize the risk for any given target return. The first step in MPT is to quantify ex ante. measures of [risk and return](Lecture%207-Risk%20and%20Return%20of%20Bonds.md) for the appropriate set of assets. A key element is to define risk. Typically, for mathematical tractability, standard deviations or variances are chosen as the measures of risk.. However, an asymmetric measure of risk, one that focuses on [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) below a specified target or. benchmark return level, can also be used.12 These asymmetric risk measures are also referred to as downside-risk measures. These measures use an intuitive measure of risk that focuses on return. dispersions below a specified target or benchmark return, which is consistent with an investor's perception of risk. In practice, using a downside-risk framework produces significantly higher bond allocations relative to stocks. This composition increases [downside protection](../Financial%20Engineering/Fixed%20Income%20Derivatives/Equity%20Linked%20Note.md) while offering the same or greater level of [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md).13  

The next task is to isolate those combinations of assets that are the most efficient, in the sense of providing the lowest level of risk for a desired level of [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md), and then to select the one combination that is consistent with the risk tolerance of the investor. Alternatively, an investor answers the question, "What is the combination that maximizes the return for a targeted level of risk?" The resulting portfolios are referred to as the [efficient portfolios](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Mean-Variance%20Efficient%20Returns%20and%20Pricing%20Fac.md) in the language of modern [portfolio theory](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20III%20THE%20PLAYERS/Chapter%2011%20-%20Individual%20Investors-A%20Survey%20of%20Modern%20Investment%20Theory/A%20Brief%20History%20of%20Investment%20Thought.md). The combination of all [efficient portfolios](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Mean-Variance%20Efficient%20Returns%20and%20Pricing%20Fac.md) is plotted to outline the [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md), where each efficient [portfolio](.md)'s [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md) is plotted on the vertical axis while the standard deviation (or risk) is plotted on the horizontal axis.  

Assume you have two risky securities-a stock [investment](.md) and a bond [investment](.md)-with the following descriptive statistics:  

Table 1 Hypothetical annualized descriptive statistics for two risky securities   


<html><body><table><tr><td rowspan="2"></td><td rowspan="2">[Expected Return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md)</td><td colspan="2">Standard Deviation Correlation</td></tr><tr><td>12%</td><td>12% -0.40</td></tr><tr><td>Stocks Bonds</td><td>6%</td><td>3%</td><td></td></tr></table></body></html>  

The task is to pick the weights ( $w_{S}$ and $w_{B}$ ) such that they sum to one and the [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md) of the [portfolio](.md) ( $w_{s}r_{s}+w_{B}r_{B}$ , where r stands for the [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md)) is maximized for any given level of [portfolio](.md) risk. There are a number of ways to define risk, but the most common way is to define it as the Standard deviation of returnse $(s_{P}=\sqrt{w_{S}^{2}s_{S}^{2}+w_{B}^{2}s_{B}^{2}+2w_{S}w_{B}s_{S}s_{B}\rho_{S B}}$ , where s is the standarde deviation and. $\rho$ is the correlation coefficient). Alternatively, an efficient [portfolio](.md) can be thought of as the [portfolio](.md) that minimizes the risk for any given level of [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md).  

![](755a0dda2ccf02927c15d2a24fb3669a470b446ac4f467131342f8d77eb92a78.jpg)  
Figure 1 [Efficient Frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md) from hypothetical inputs  

An alternative way to visualize the [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md) is to think of the [efficient portfolios](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Mean-Variance%20Efficient%20Returns%20and%20Pricing%20Fac.md) as representing different [probability distributions](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) an investor must select from. For example, two of the [efficient portfolios](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Mean-Variance%20Efficient%20Returns%20and%20Pricing%20Fac.md) (return of $6.59\%$ and $7.87\%$ ) can be represented as the following two distributions:  

![](44e59afbef9b08e7f0c57a280a0572174bc0d7bb8ab0e3e9ecfb19f2c3ac1230.jpg)  
Figure 2 [Probability distributions](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) of two different hypothetical [efficient portfolios](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%209%20-%20Factor%20Models/Mean-Variance%20Efficient%20Returns%20and%20Pricing%20Fac.md)  

The traditional [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md) may mislead an investor into thinking that the security's [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) will average out over time to the [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md) with the [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) jumping up and down according to the standard deviation of [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md). In fact, the [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md) reflects the probability distribution of [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) over a certain time horizon. It does not tell the investor about the path the security will take over the [investment](.md) horizon, but only about the projected terminal values and the uncertainty thereof. Which specific distribution is most attractive is not obvious, but instead depends on [investor preferences](../Financial%20Instruments/Financial%20Derivatives%20and%20Quantitative%20Methods/Risk%20Preferences.md).  

Central to modern [portfolio theory](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20III%20THE%20PLAYERS/Chapter%2011%20-%20Individual%20Investors-A%20Survey%20of%20Modern%20Investment%20Theory/A%20Brief%20History%20of%20Investment%20Thought.md) is the premise that [investment](.md) decisions are made to achieve an optimal risk/return tradeoff from the available opportunities. The critiques of MPT typically focus on. the inappropriateness of particular measures of risk or return. Because [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md)-just like investing-is forward-looking, risk or return measures should be based on future [expectations](../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md), but most implementations are based on historical averages, standard deviations, and correlations..  

The optimization of the [portfolio](.md) allocation can be achieved in either one stage or two. In the singlestage optimization, allocations are determined by satisfying both active and systematic risk preferences. simultaneously. In the two-step process, investors first choose a long-run benchmark [portfolio](.md) based on the risk-return relationships for bearing systematic risk. Once this allocation is established, the investor then decides how to structure the [portfolio](.md) using a combination of passive and actively managed. strategies. The allocation to active strategies can be structured by maximizing the trade-off between expected [portfolio](.md) return and active risk while holding the level of systematic risk constant as embodied in the long-run benchmark allocation. The two-step process is the typical one used by advisors, in which they first determine a client needs specified exposures to broad asset classes and then use specific mutual funds in order to populate the [portfolio](.md)..  

As noted above (page three), the two-step process is a sub-optimal way of optimizing a [portfolio](.md): active managers bring systematic risk to a [portfolio](.md) and that systematic risk exposure can change over time..   
The investor must evaluate active risk and systematic risk jointly, not separately. All sources of.   
systematic risk and active risk need to be monitored and evaluated to make sure they are consistent.   
with the client's risk preferences..  

For example, domestic equity exposure could be modeled by using three asset classes represented by the Russell Top 200, the Russell Mid Cap index, and the Russell Small Cap index. Using the historical riskreturn numbers as September 30, 2007 with monthly [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) would have given the following descriptive statistics as inputs to an optimization tool:  

Table 2 Average and Standard Deviation (annualized) of Monthly [Returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) for indices, from April 1999 to September 2007. Source: Zephyr Allocation Advisor   


<html><body><table><tr><td>IndexName</td><td>AverageMonthlyReturn (annualized)</td><td>StandardDeviationofMonthly [Returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) (annualized)</td></tr><tr><td>RussellTop200</td><td>13.23%</td><td>14.79%</td></tr><tr><td>RussellMidcap</td><td>15.57%</td><td>16.02%</td></tr><tr><td>RussellSmallCapCompleteness</td><td>10.12%</td><td>19.09%</td></tr></table></body></html>  

Table 3 Correlations of monthly [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) for indices, from April 1999 to September 2007. Source: Zephyr Allocation Advisor   


<html><body><table><tr><td></td><td>RussellTop200</td><td>Russell Midcap</td><td>Russell Small Cap Completeness</td></tr><tr><td>RussellTop200</td><td>1.00</td><td>0.8970</td><td>0.7758</td></tr><tr><td>Russell Midcap</td><td>0.8970</td><td>1.00</td><td>0.9473</td></tr><tr><td>Russell Small Cap Completeness</td><td>0.7758</td><td>0.9473</td><td>1.00</td></tr></table></body></html>  

A [portfolio](.md) with a target risk of. $14.76\%$ (the minimum risk [portfolio](.md), assuming non-negative investments in each index), would have been. $12.4\%$ in the Russell Top 200 index and. $87.6\%$ in the Russell Midcap. index. The average return for this [portfolio](.md) was $13.52\%$  

For purposes of illustration, I selected a mutual fund benchmarked against the Russell 2o00 as a substitute for the Russell Small Cap Completeness index. With this specific substitution, the same target Brian Jacobsen, Wells Fargo Funds Management, LLC $\circledcirc9$ risk $(14.76\%)$ would have been achieved with a $37.4\%$ allocation to the Russell Top 200, a $30.8\%$ allocation to the Russell Midcap, and a $31.8\%$ allocation to the mutual fund. The [portfolio](.md)'s averagee. return would have also increased from. $13.52\%$ to $14.40\%$ . This change in allocations partially reflects. the fact that active risk and systematic risk are not necessarily separable.  

# Market Weighted Portfolios  

Instead of generating forecasts of risks and [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) and optimizing a [portfolio](.md) based on that outlook, some prefer to use the competitiveness of markets to develop asset allocations. If markets are. competitive, in the sense of incorporating relevant information in current prices, then the market allocation should be an optimal allocation for the "typical" investor. In this framework, the market allocation is a good starting point for an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md), but then the question becomes determining the market allocation. One way to do is by calculating the [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md) of the various assets, commonly done by multiplying the closing price of the security or securities in question by the number. of securities outstanding. Some index providers provide this information in quarterly commentaries. One relatively recent innovation is to base the [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md) only on free-floating shares, i.e. those that that are readily available to domestic investors.  

There is a philosophical question as to whether multiplying the market price by the shares outstanding is the best way to calculate the [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md): If only two shares of stock sold for $\$100$ , would it be appropriate to say that all shares of that company's stock are worth $\$100$ a piece? Market prices are only indicative of what was paid, not what can be received for a hypothetical trade. If markets are continuous, in the sense that prices do not make large jumps, then this method of calculating [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md) is not too objectionable. However, if prices can jump and the size of the order matters, then this method of calculating the [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md), which goes into determining the relative weights of securities in a [portfolio](.md), seems suspect. An alternative is to use a [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) weighted metric, where what matters is the relative dollar trading volume of securities. Figure 3 and  

Figure 4 show how there is no statistically discernible relationship between the dollar trading volume of a security and the calculated [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md) of a company, meaning that the choice of metric could have a significant impact on [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md)..  

![](643a2f49f537585a47036c2ed53282ddb1f7868b1a1d11a765d3edebce2fc253.jpg)  
Figure 3 Trading volume regressed on market. capitalization for third quarter, 2004, for Russell 3000 constituents.  

![](29c69f6047487f5e34c426c2c3a5ab20284cc8dbeaf07fd37a0400082ae3c69f.jpg)  
Figure 4 Trading volume regressed on [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md) for second quarter, 2009, for Russell 3000 constituents.  

Different weighting schemes reflect different views about how security prices will likely move. For.   
example, a price-weighted [portfolio](.md) is equivalent to a momentum investing strategy. An equal-.   
weighted strategy or a fundamental-weighted [portfolio](.md) is equivalent to a contrarian [investment](.md).   
strategy.14 The trading volume weighting scheme is not materially different from an equally-weighted.   
scheme. Based on this evidence, an equal-weighted [portfolio](.md) may be the best starting point for an allocation called the normal allocation or the market allocation..  

Deviations from the normal allocation can be due to an idiosyncratic risk exposure or goal of the client (e.g., your client's skills are primarily marketable in the information technology sector, which means his future income is already exposed to risks in that particular sector). [Institutional investors](../Financial%20Markets/Financial%20Trading%20and%20Markets/Chapter%204%20Institutional%20Trading.md) as well as individuals have to face the problem of managing their assets in a way that ensures that all their. liabilities (including future liabilities) can be fully met and their financial goals achieved. This type of [investment](.md) management is widely known as asset and liability management (ALM), 15 in which an. optimal strategy for a client consists of achieving financial and personal goals under a given set of financial constraints. In contrast to ordinary financial planning methods, the ALM approach. simultaneously considers the joint uncertain evolution of assets and liabilities. This approach can be superior if, for example, assets and liabilities share common [risk factors](../Financial%20Instruments/Assignments/PSET%206-%20Financial%20Instruments.md) and liabilities hedge some assets. For example, an individual who drives a lot has exposure to oil price risk: as the price of oil increases, the cost of driving most likely increases as well. If that individual also owns shares of stock in an oil company, the asset provides offsetting oil-price-risk exposure..  

All an individual's assets and liabilities-whether easily quantifiable or not-should be considered part of the individual's economic exposure. It is not appropriate to segregate an individual's exposures into [investment](.md) and operating categories. An individual's [portfolio](.md) should be viewed holistically, with all significant exposures considered.  

# Asset Allocation and Asset Location Should Be Considered Jointly  

When it comes to [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md), asset location also matters: different ways in which you title an asset.   
or the type of account used carries profound tax and legal implications. Assets and asset strategies.   
should ideally be allocated to different vehicles based on their tax efficiency. However, the primary.   
purpose of developing an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) strategy is to achieve the client's goals, not just to have a tax efficient [portfolio](.md). Estate planning attorneys often say, "The tax tail should not wag the estate-plan.   
dog." A client might have very good reasons for subordinating tax efficiency to other goals..  

Some basic rules of asset location arise from the differential tax treatment of different types of accounts, as outlined by Waggle and Englis (2o0o). Typically, long-term equity holdings should be in nonretirement accounts while taxable bonds should be in retirement accounts to improve tax efficiency.. Another basic rule is that only those in the highest marginal tax bracket should hold municipal bonds. Of course, there are many exceptions to these basic guidelines..  

The methods and tools used for determining optimal asset allocations have historically been established based on the needs of [institutional investors](../Financial%20Markets/Financial%20Trading%20and%20Markets/Chapter%204%20Institutional%20Trading.md). While the strategies that [institutional investors](../Financial%20Markets/Financial%20Trading%20and%20Markets/Chapter%204%20Institutional%20Trading.md) utilize may Brian Jacobsen, Wells Fargo Funds Management, LLC O12 be quite complex, they often have a straightforward result. First, assets are generally housed in one taxexempt entity. Second, the assets are used to meet a specific goal, which is to support relatively welldefined payments on a regular basis over time. The situation for private individuals is significantly different. Private client assets often reside in different locations, with different taxability, and are used to fund multiple goals. An advisor needs to locate assets in the most advantageous places and in the most advantageous mix to have the highest probability of meeting various client goals.16  

# When should an allocation deviate from the norm?  

# Allocations Should Change Over Time  

Because of the changing nature of clients and the economy, you cannot systematically favor a single asset class. Overly simplistic or extreme strategies are a disservice to the client. Instead, a systematic set of rules is needed to transform [expectations](../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) into a strategy.17 In Bodie, [Merton](../Credit%20Markets/Credit%20Markets%20Session%205.md), and Samuelson (1992), the authors highlight the importance of an individual's labor income (also referred to as human capital) in determining an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) strategy. Because human capital is usually less risky than. [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) on equities, they analogize human capital to a [fixed income](../Fixed%20Income%20Asset%20Pricing/Lecture%20Notes%20Bonds,%20%20Preferred%20Stock,%20%20and%20Structured%20Products.md) security. Early in an investors' working career, the investors' total [portfolio](.md), which includes both human and financial capital, is dominated by bond-like human capital. As a result, the individual's financial capital should be concentrated in equities. At any given age, the greater the flexibility to alter one's labor supply, the greater the amount that should be invested in risky assets, because investors may be able to offset financial losses by working more. Bodie (2o03) says that the value, [riskiness](../Financial%20Instruments/Financial%20Derivatives%20and%20Quantitative%20Methods/Risk%20Preferences.md), and flexibility of a person's Iabor earnings are of first-order importance in optimal [portfolio](.md) selection at each stage of the life cycle.19  

One short-coming of analogizing human capital to a fixed-income instrument is that it downplays the "optionality" of labor: workers can choose to change jobs or extend/contract their working life. Thus it. may be more appropriate to compare human capital to a convertible bond or a bundle of a bond and an option, which would justify a higher allocation to active management strategies as individuals age. As human capital loses its optionality with age, financial wealth should gain optionality.2o Rarely do clients. want to consider their human capital as part of the [investment](.md) process, especially since human capital decays with age. However, just as advisors must discuss whether clients need life insurance, which raises. questions about mortality, a holistic approach to financial planning requires recognizing the role of both. human capital and financial capital in building an appropriate [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) strategy..  

# Liquidity is Valuable and Its Price Changes with Market Conditions  

Allocations should be modified according to an investor's need-or lack of need-for [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md). Investors with a short [investment](.md) horizon have a need for [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) and, therefore, should have a relatively higher proportion of the [portfolio](.md) in liquid securities. [Liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) does not just refer to how quickly, but also to how predictable the price at which, a security can be sold. Thus, for a [fixed income](../Fixed%20Income%20Asset%20Pricing/Lecture%20Notes%20Bonds,%20%20Preferred%20Stock,%20%20and%20Structured%20Products.md) allocation, a shortterm investor should have more assets in cash equivalents such as [money market funds](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%206-%20Bank%20Runs/Breaking%20the%20Buck.md). Long-term  

investors have less of a need for [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) and should therefore place more of an emphasis on assets such as [private equity](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20III%20THE%20PLAYERS/Chapter%2014%20-%20Private%20Equity,%20Pension,%20and%20Sovereign%20Funds/Private%20Equity.md), [commodities](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20I%20RELATIVE%20VALUE%20BUILDING%20BLOCKS/Chapter%203%20-%20Futures%20Markets/Futures%20Not%20Subject%20to%20Cash-And-Carry.md), real estate, and equities.  

[Liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) is also important because it helps determine how [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) should be measured for the inputs to a [portfolio optimization](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20III%20THE%20PLAYERS/Chapter%2011%20-%20Individual%20Investors-A%20Survey%20of%20Modern%20Investment%20Theory/The%20Modern%20Portfolio%20Theory%20and%20the%20Capm.md) system. Investors with only one month of cash need to be concerned about. one-month [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) on the various asset classes since they are living "one month at a time." Investors with six months of cash needs to consider risks and [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) over a six-month holding period since the. worst-case scenario is that the investor will run out of cash in six months and need to recapitalize.  

At different times, the market will place a greater or lesser premium on [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md). When the market values [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) highly, [illiquid assets](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) sell at a discount. Changing [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) premiums can lead to marginal [portfolio](.md) changes according to the client's [investment](.md) horizon. One way to measure the [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) premium is through the steepness of the yield curve.1 Generally, low [short-term rates](../Financial%20Markets/Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%208/Volatility%20and%20Convexity.md) relative to longterm rates indicate a higher [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) premium as individuals are willing to lend money at lower rates for shorter periods of time. Cash, which is typically thought of as the most liquid asset, has no explicit return. Its value is in its "[currency](../Financial%20Instruments/Lecture%20Notes-%20Financial%20Instruments/Teaching%20Note%201-%20Forward%20Rates%20Agreement/Forwards%20and%20Futures%20Notes.md)," or its ability to be used immediately to satisfy a current consumption need.  

Another way to measure the market's taste for [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) is to calculate investors' implied holding period. The [market capitalization](../Advanced%20Financial%20Analysis%20and%20Valuation/Financial%20Ratios/Price-to-Sales%20Ratios%20in%20Stock%20Valuation.md) of a company divided by the daily market value of trades results in the days. shares outstanding. The lower the days shares outstanding, the shorter investors' holding periods and, implicitly, the more investors are valuing [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md)..  

The most liquid security is usually the "risk-free" security, often defined as the 30-day Treasury bill. In reality, there is no one universal risk-free security, because what is risk-free depends on the client's funding needs. From a client's perspective, a [risk-free portfolio](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%204%20-%20State%20Prices/Definitions%20and%20Immediate%20Consequences.md) might be one that employs a cash-flow matching scheme in which cash becomes available just as it is needed. Portfolios structured this way are sometimes called laddered portfolios.22  

# Conditional Asset Allocation  

All [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md)--whether strategic or tactical-should be considered dynamic.3 Asset class weights in a [portfolio](.md) should remain fixed only if the expected [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) and risks of various investments and the investor's risk exposure and capacity remain static. Obviously, such is not the case. Thus even a strategic [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) should allow for changing asset class weights as the client's situation or the economic environment changes.  

Differences in inputs, especially correlation coefficients amongst [investment](.md) alternatives, can have a. significant impact on the weighting of asset classes in a [portfolio](.md) and on the [portfolio](.md)'s [risk and return](Lecture%207-Risk%20and%20Return%20of%20Bonds.md) characteristics. Historical data show a great deal of variability and can be misleading indicators of future. behavior.24 Most [forecasting](../Advanced%20Financial%20Analysis%20and%20Valuation/Lecture%20Notes%20Advanced%20Financial%20Analysis%20and%20Valuation/Week%202/Week%202%20Fundamentals%20Of%20Forecasting.md) uses key historic economic and financial data to develop a macroeconomic model of future [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md). [Asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) under this paradigm is called conditional [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md).25  

# Historical Analogies  

The difference between using historical averages or forecasts based on a macroeconomic model can be significant. Looking for historical analogies to the present situation can be difficult because while different situations may be similar, they are never identical.26 By using a certain time period to develop your averages, standard deviations, and correlations, effectively you are saying that the near future is a random sample from the relevant historical time period.  

For example, from March 2009 to the end of November 2009, the price of gold and stock prices (as measured by the S&P 500) increased dramatically while the trade-weighted value of the U.S. dollar. dropped. We can look at other periods of times in which these three events took place and see how. prices moved subsequently. To do this, we measured trailing three-month [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) of the spot price of gold, the S&P 500, the International Monetary Fund's nominal effective exchange rate index for the dollar, and the Barclays Capital U.S. Aggregate Bond index. Monthly data were available on all these indices from April 30, 1976 to November 30, 2009. For any month in which the trailing three-month gold and stock prices rose while the dollar declined, we calculated the total [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) for the next three months. According to a robust t-test, the mean [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) of bonds were statistically less than the return on gold. Additionally, gold outperformed the dollar. The historical analogy can inform our forecasts of the annualized average [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md), standard deviations, and correlations as shown in Table 4.  

Table 4 Annualized descriptive statistics based on forward three month [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) when the previous three month: had increased stock prices and gold prices and a declining dollar   


<html><body><table><tr><td></td><td>[Expected Return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md)</td><td>Standard Deviation nCorrelation</td></tr><tr><td>S&P500</td><td>9.16%</td><td>13.01% .105</td></tr><tr><td>BarclaysIndex</td><td>6.03%</td><td>6.75%</td></tr></table></body></html>  

# Statistical Analysis  

Farrell (1989) offers a concise method for generating inputs for an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) model. The first step is to asses the basic financial characteristics of each asset class-what are the rights of the security holders, the position in the [capital structure](../Advanced%20Financial%20Analysis%20and%20Valuation/Introduction%20to%20Corporate%20Finance.md) of the issuer, etc. Second, evaluate how, given these characteristics, the asset class is likely to react to changing [economic conditions](../International%20Finance/Bridgewater/Chapters/US%20Debt%20Crisis%20and%20Adjustment%20(2007–2011).md). Third, examine how. asset classes have historically reacted to economic changes. Finally, develop scenarios and assign probabilities to them to generate forecasts of return, variability, and correlation. Of course, like most methods, the difficulty is in the implementation. Arnott and von Germeten (1983) argue that though it. is easy to use current yield for cash equivalents, yield to maturity for bonds, and the dividend discount. model rate of return for equities, it is also helpful to incorporate other information, like [inflation](../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md) and [economic conditions](../International%20Finance/Bridgewater/Chapters/US%20Debt%20Crisis%20and%20Adjustment%20(2007–2011).md). Bodie (2003) said that [portfolio](.md) managers can and should make greater use of  

information about the [term structure of interest rates](../Financial%20Engineering/6.%20A%20Brief%20Introduction%20to%20Stochastic%20Calculus.md) and implied volatilities embedded in the prices of [derivatives](../Financial%20Markets/Financial%20Trading%20and%20Markets/Chapter%209%20Arbitrage%20and%20Hedging%20With%20Options.md), such as swaps and options.  

You can statistically estimate the inputs into the [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) optimization by using a macroeconomic model. A model not only allows you to derive an [expected return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md), but also to calculate the standard. error of the forecast, which reflects the uncertainty around the forecast. You can also develop a forecast of the correlations by using the rules for adding two random variables: If you forecast random variables X and Y, then you can develop a forecast for. $0.5\mathsf{X}{+}0.5\mathsf{Y}$ (or any other fixed combination). From. the standard errors, you can then derive the forecasted correlation between X and Y. This is because. the standard error of a [portfolio](.md) of random variables is related to the standard errors of the individual random variables and the correlation of the random variables. Because the forecasts give the standard. errors, you can back-out the correlations..  

For example, assume you want to develop a one-year-ahead forecast of the total return on the S&P 500 and the total return on the Barclays Capital U.S. Aggregate index as of October 31, 2009 based solely on the preceding one-year percentage change in U.S. personal income. There are many issues surrounding the use of macroeconomic data for forecasts: First, the data are available only with a lag-the October personal income data is not available until November. Second, some of the data are subject to revision. To deal with the lag issue, it is easy enough to use lagged data, but the second issue is more difficult to overcome since most data sources have only archived the revised data. These are practical difficulties to overcome, but we will illustrate our method under the assumption that the data are not revised.27 To. illustrate, we will use the trailing one-year percentage change in U.S. personal income to forecast the one-year-forward total [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md). To build the model, we will use the trailing one-year percentage change in U.S. personal income from December 1987 to September 2008. The S&P and Barclays one-year. forward [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) were measured from January 1988 to October 2008. From the estimated models, the trailing one-year percentage change in U.S. personal income as of September 2009 was used to generate one-year-ahead forecasts.  

The estimated models are as follows:  

S& P $500\%$ return from October 31, 2009 to October 31, $2010=12.48-0.32\times\%$ change in Personal Income from September 30, 2008 to September 30, 2009.  

Barclays $\%$ return from October 31, 2009 to October 31, $2010=5.56\cdot0.05\times\%$ change in Personal Income from September 30, 2008 to September 30, 2009.  
$\%$ in Stocks and $\%$ in Bonds $\%$ change from October 31, 2009 to October 31, $2010=9.02-0.19\times$ $\%$ change in Personal Income from September 30, 2008 to September 30, 2009.  

Associated with each coefficient is a standard error of the estimate, which can be used to indicate whether or not the estimate is statistically significant. For the preceding models, the intercept terms are. statistically significant at least at the. $5\%$ level. The slopes are significant at least at the. $10\%$ significance level.  

Brian Jacobsen, Wells Fargo Funds Management, LLC O16  

The Bureau of Economic Analysis reported that personal income declined by $1.57\%$ from September 2008 to September 2009. This means the S&P 500 was forecasted to rise by $12.99\%$ , the Barclays index to rise by $5.64\%$ , and the 50/50 split to rise by $9.31\%$ from October 2009 to October 2010. In addition to. these "expected [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md)," we also need forecasts for the standard deviations and the correlation.  

Most statistical packages include as an output the standard error of the estimate. In Excel, using the. LINEsT function (an array function that requires special handling and that gives a "linear estimation"),. the standard error of the estimate is in the third row and second column of the output. The standard errors for the S&P 500, Barclays index, and 50/50 [portfolio](.md) are. $17.91\%$ $2.25\%$ and $9.69\%$ , respectively. These are not quite the standard deviations of [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) we need as inputs for an optimization. This is. because our forecast is based on data not included in the set of data used to develop the estimated model. If the year-on-year change in September personal income data was equal to the average of the historical data used to develop the estimated model (positive. $7.53\%$ , then the adjustment would be easy. Because the September number was below average, we need to adjust the standard errors. If. ${}^{\prime\prime}{\mathsf{S}}^{\prime\prime}$ stands for the standard error from the linear estimation, and there are $"\mathfrak{n}^{\prime\prime}$ observations in the linear estimation (in our case, we had 250 observations), and. $\textsf{X}$ is the observation of the personal income we. are using as the basis for our forecast, then the standard error is. $s\sqrt{1+\frac{1}{n}+\frac{\left(X-{\overline{{X}}}\right)^{2}}{\displaystyle\sum_{i=1}^{n}\left(X_{i}-{\overline{{X}}}\right)^{2}}}$ . In this.  

expression, $\bar{X}$ is the average value of the year-on-year change in personal income from the historical data series $(+7.53\%)$ and $\sum_{i=1}^{n}\Bigl(X_{i}-\overline{{X}}\Bigr)^{2}$ is the sum of the squared deviations of each personal income observation from the average. In our example, this is equal to 4,973.92. Based on this information, we have our forecasts for the standard deviations of [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) for the S&P 500, the Barclays index, and the 50/50 split as $18.27\%,$ $2.30\%$ , and $9.88\%$ respectively. Please note: because the forecast is based on an. observation that is away from the mean of the independent variables, there is an "[inflation](../International%20Finance/Bridgewater/Principles%20For%20Navigating%20Big%20Debt%20Cycles/Part%20II%20Detailed%20Case%20Studies/German%20Debt%20Crisis%20andHyperinflation%20(1918–1924)/War%20Economies%20and%20Hyperinflation.md)" of the uncertainty.  

The next step is to get the forecasted correlation between the S&P 500 and the Barclays index. This is. why we needed the forecast of the 50/50 split (or any other fixed linear combination). The standard error of the 50/50 split. $(s_{50/50})$ is related to the weights in each index ( $w_{S P}=0.5,w_{B}=0.5\vert$ , the standard error of the S&P 500 $\mathrm{~\boldmath~\left~\left~\right.~\left.~\right.~}S_{S P}\mathrm{~\bf~\right.~}$ , the standard error of the Barclays index. $\big(S_{B}\big),$ and the correlation. between stocks and bondse $(r_{S B})\{\sf b\gamma}s_{50/50}^{2}=w_{S P}^{2}s_{S P}^{2}+w_{B}^{2}s_{B}^{2}+2w_{S P}w_{B}s_{S P}s_{B}r_{S B}$ . From the forecasts, wee have all these except the correlation. It is a matter of simple algebra to solve for the correlation:. $r_{S B}={\frac{s_{50/50}^{2}-w_{S P}^{2}s_{S P}^{2}-w_{B}^{2}s_{B}^{2}}{2w_{S P}w_{B}s_{S P}s_{B}}}$  

Table 5 Forecasts for October 2009 to October 2010 [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) based on simple macroeconomic model   


<html><body><table><tr><td colspan="2">[Expected Return](Lecture%201-%20Probability%20Distributions%20of%20Returns.md)</td><td colspan="2">Standard DeviationCorrelation</td></tr><tr><td colspan="2">SP500</td><td>12.99% 18.27%</td><td>0.614</td></tr><tr><td colspan="2">BarclaysIndex</td><td>5.64% 2.30%</td><td></td></tr></table></body></html>  

With these inputs, we can construct an [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md) based on forecasted [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) and risks from our simple macroeconomic model. Note the differences between the forecasted [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) and standard deviations for the macroeconomic-based model and the historical model shown in Table 4: in the macroeconomic model, stocks have a higher forecasted return, bonds are expected to do slightly worse, there is increased risk with stocks, but decreased risk with bonds, and the correlation is higher. These small differences can sometimes be significant. One option is to take a weighted average of the. different methods, depending on your confidence in each..  

[Asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) is a dynamic process. As Jahnke (2o04) wrote, the practice of setting and sticking with a static [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) only makes sense in a world where asset class return [expectations](../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) do not vary.   
with time. Even with efficient markets, static [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) can only be justified by employing highly.   
unrealistic assumptions.8 In creating the framework for Modern [Portfolio Theory](../Financial%20Markets/Financial%20Engineering%20and%20Arbitrage%20in%20the%20Financial%20Markets/PART%20III%20THE%20PLAYERS/Chapter%2011%20-%20Individual%20Investors-A%20Survey%20of%20Modern%20Investment%20Theory/A%20Brief%20History%20of%20Investment%20Thought.md), Markowitz did not.   
suggest that [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) are stable and an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) should stay fixed. Rather, he acknowledged that.   
the [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) change and the allocation needs to stay current..  

Those involved in the [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) decision should not just rely on historical averages, standard deviations, and correlations in creating portfolios, in part because the practice of extrapolating [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) generally results in high expected [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) at market tops and low expected [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) at market bottoms. These are the exactly wrong times to have those [expectations](../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md). Active [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) does not mean market timing, but it does mean being cognizant of the economic [fundamentals](../Advanced%20Financial%20Analysis%20and%20Valuation/Lecture%20Notes%20Advanced%20Financial%20Analysis%20and%20Valuation/Week%202/Week%202%20Fundamentals%20Of%20Forecasting.md).29 There is a lot of information contained in economic data that can help build [expectations](../Fixed%20Income%20Asset%20Pricing/Fixed%20Income%20Lecture%20Notes/FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md), which should be reflected in an [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md).30  

# The Bottom Line  

Putting this all together suggests that each individual client's [portfolio](.md) should be custom optimized. In a framework in which you have short-term, medium-term, and long-term investors, you will have efficient frontiers for each time horizon because what is optimal in the short-run is not necessarily optimal in the Iong-run. You will also have different efficient frontiers due to the different allowable investable assets.  

As Figure 5 (below) illustrates, a basic framework for [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) is to think of nine different types of investors, categorized according to the client's [investment](.md) horizon (short-, medium-, and long-term) and risk tolerance (conservative, moderate, and aggressive). As a result, instead of one [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md), you will have at least nine.  

Brian Jacobsen, Wells Fargo Funds Management, LLC O18  

This is a highly stylized framework as each dimension should be thought of as a continuum and not simply a matrix of boxes. We center the framework on the "normal allocation" (equally weighted, as described above), defining it as the medium-term/moderate allocation. The [investment](.md) horizon and risk tolerance is always measured relative to the normal allocation. The normal allocation may change over time, depending on the economic environment and various opportunities.  

Figure 5 [Asset Allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) Framework   


<html><body><table><tr><td rowspan="2">AllocationFramework</td><td rowspan="2"></td><td colspan="3">Risk Tolerance</td></tr><tr><td>Conservative</td><td>Moderate</td><td>Aggressive</td></tr><tr><td rowspan="3">[Investment](.md) Horizon</td><td>Long-term Medium-term</td><td>Bias toward self-</td><td>Short [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) (e.g., fewer U.s. Treasuries)</td><td>Bias away from</td></tr><tr><td></td><td>liquidating securities (e.g., more [fixed income](../Fixed%20Income%20Asset%20Pricing/Lecture%20Notes%20Bonds,%20%20Preferred%20Stock,%20%20and%20Structured%20Products.md))</td><td>Neutral</td><td>self-liquidating Securities (e.g., more equity)</td></tr><tr><td>Short-term</td><td></td><td>Long [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) (e.g., more U.s. Treasuries)</td><td></td></tr></table></body></html>  

Once an advisor develops the efficient frontiers, they can then be customized for investors' individual goals and constraints. An advisor can help a client articulate those goals, identify constraints, and develop a coherent strategy.31 The client's risk preferences will dictate which types of securities go into the investable universe. The client's need for [liquidity](../Financial%20Markets%20and%20Institutions/III.%20Liquidity%20of%20Assets/Class%205-%20Private%20Information,%20Liquidity,%20and%20Securitization/Class%20Note%2010%20Liquidity%20and%20Class%20Note%2010%20Liquidity%20and%20Liquidity%20Managementliquidity%20management.md) will determine over which horizon risks and [returns](../Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%203%20-%20%20Assets,%20Portfolios,%20and%20Arbitrage/Assets.md) should be measured. As such, there is really no one single [efficient frontier](../Financial%20Engineering/2.%20Forwards,%20Swaps,%20Futures,%20and%20Options.md). What is efficient for one investor may be wholly inefficient and inappropriate for another investor. This is why [asset allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md) cannot be viewed as a mass production technology. At best, it is mass-customization.  

# References:  

Anson, Mark, "Strategic versus Tactical [Asset Allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md). Beta versus alpha drivers," The Journal of [Portfolio Management](../Financial%20Engineering/Fixed%20Income%20Derivatives/The%20Impact%20of%20Option%20Strategies%20in%20Financial%20%20Portfolios%20Performance.md), Winter 2004, pp. 8-22.  

Arnott, Robert D. and James N. von Germeten, "Systematic [Asset Allocation](Lecture%202-%20Asset%20Allocation%20with%20Multiple%20Risky%20Assets.md)," Financial Analysts Journal, November-December 1983, pp. 31-38.  