---
title: Pricing Forwards, Futures, Bonds, Swaps, Swaptions, Caps And Floors Under No-Arbitrage And Risk-Neutral Pricing
tags:
  - complete_market
  - derivative_pricing
  - financial_instruments
  - no_arbitrage_pricing
  - risk_neutral_valuation
aliases:
  - Derivative Valuation
  - No-Arbitrage Pricing
  - Pricing Derivatives
  - Risk-Neutral Valuation
key_concepts:
  - Expected payoffs, discounting
  - Fundamental theorem
  - Law of one price
  - No-arbitrage, riskless profit
  - Pricing PDE
  - Replicating portfolio
  - Risk-neutral probability measure

 
---
.# **Introduction**
In modern financial theory, **[no-arbitrage pricing](.md)** and **risk-neutral valuation** form the cornerstone for valuing derivative instruments. _No-arbitrage_ means there are no opportunities to make a riskless profit with zero net [investment](An%20Asset%20Allocation%20Primer.md) – put simply, markets adjust so that no “free lunch” is possible . Under this principle, the price of any financial instrument is constrained by the _law of one price_: two portfolios with identical future payoffs must have the same current price. The **[fundamental theorem](.md) of [asset pricing](Fixed%20Income%20Asset%20Pricing.md)** formalizes this: a market is [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md)-free if and only if there exists at least one **[risk-neutral probability measure](.md)** (also called an equivalent martingale measure) under which discounted asset prices follow a martingale (have _fair game_ expected changes) . Intuitively, a _risk-neutral measure_ is a set of probabilities such that all assets earn the [risk-free rate](Black%20Scholes%20Derivation.md) $r$ – investors are “indifferent to risk” under this measure, so expected [returns](Assets.md) in the [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) model equal $r$. [Pricing derivatives](.md) in an [arbitrage-free market](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) can thus be done by taking _expected payoffs under the [risk-neutral probabilities](Financial%20Instruments.md) and discounting at the risk-free rate_. This is the essence of **[risk-neutral pricing](Financial%20Mathematics%20Course.md)** .

**Risk-Neutral Valuation:** If $X_T$ is a payoff at future time $T$, and $B(0,T)=e^{-rT}$ is the [discount factor](Discount%20Factors.md) (for constant $r$), then the [no-arbitrage price](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) at time 0 is given by the discounted [risk-neutral expectation](Risk-Neutral%20Probabilities.md): $$V_0 = B(0,T);\mathbb{E}^Q[X_T] = e^{-rT},\mathbb{E}^Q[X_T],,$$ where $\mathbb{E}^Q$ denotes expectation under the [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md) $Q$. For example, the [no-arbitrage forward price](Appendix%205.A%20Taxes%20and%20the%20Forward%20Price.md) $F_0(T)$ of an asset for delivery at time $T$ must equal $\mathbb{E}^Q[S_T]$ grown at $r$, so $F_0(T)=S_0 e^{rT}$ (we will derive this shortly). Similarly, the [no-arbitrage price](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) of a call option is $C_0 = e^{-rT},\mathbb{E}^Q[(S_T - K)_+]$ . These results hold _regardless of investors’ risk aversion_, relying only on [arbitrage arguments](Forward%20Contracts%20and%20Forward%20Prices.md) and [replication](Forward%20and%20Futures%20Contracts.md). In a **complete market** (one where every payoff can be replicated by trading [underlying securities](Rate%20and%20Price%20Trees.md)), the [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md) is unique, and thus derivative prices are uniquely determined by no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md).

**[Replication](Forward%20and%20Futures%20Contracts.md) and [Pricing](Arbitrage%20Pricing%20of%20Derivatives.md):** [No-arbitrage pricing](.md) can be approached via two dual perspectives: (1) constructing a **[replicating portfolio](.md)** that perfectly replicates the derivative’s payoff and equating its cost to the derivative’s price (the classic approach used in the Black–Scholes derivation), or (2) directly computing the **risk-neutral expected payoff** and discounting. Both approaches yield the same result when markets are [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md)-free. In continuous time, [replication](Forward%20and%20Futures%20Contracts.md) leads to a **[pricing PDE](.md)** (e.g. the Black–Scholes equation), while risk-neutral valuation uses probabilistic tools (e.g. martingales and expectation under $Q$). In practice, [risk-neutral pricing](Financial%20Mathematics%20Course.md) is often more convenient for complex [derivatives](Chapter%209%20Arbitrage%20and%20Hedging%20With%20Options.md): one assumes the [underlying asset](Risk%20Neutral%20Pricing%20of%20Options.md)’s **drift** under $Q$ is the [risk-free rate](Black%20Scholes%20Derivation.md) $r$, simulates or analytically evaluates the payoff’s expectation, then discounts. Below, we will apply these principles to price a range of instruments: [forwards](Forwards%20and%20Futures.md), [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md), bonds, swaps, swaptions, caps, [floors](Caps%20and%20Floors.md), and related [derivatives](Chapter%209%20Arbitrage%20and%20Hedging%20With%20Options.md). We develop formal [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) formulas with **step-by-step derivations**, using consistent notation and an academic tone. Key results from foundational texts (Hull, Shreve, Duffie, etc.) and seminal papers (Black–Scholes 1973, Black 1976) are highlighted along the way.

**Notation:** We let $S_t$ denote the spot price of an [underlying asset](Risk%20Neutral%20Pricing%20of%20Options.md) (stock, commodity, etc.) at time $t$. $P(t,T)$ denotes the price at time $t$ of a zero-coupon bond paying $1 at maturity $T$ (so $P(0,T)=e^{-rT}$ if $r$ is constant). We write $B(t)$ for the **money-market account** (bank account) accruing at the risk-free rate, so $B(t)=e^{rt}$ under continuous compounding. For stochastic interest rates, $P(t,T)=e^{-\int_t^T f(t,u),du}$ is determined by the yield curve or short-rate model (we assume deterministic $r$ for simplicity unless stated). Expectations $\mathbb{E}^Q[\cdot]$ are under the risk-neutral measure $Q$. For options, $(x)^+ = \max{x,0}$ indicates the positive part. We use $\Phi(\cdot)$ for the standard normal CDF, and will present formulas in **LaTeX** for precision. Each section ends with a summary of key results, and a final section provides further reading from classic references for deeper study.

**No-[Arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) and Risk-Neutral Foundations**

Before diving into specific instruments, we review the theoretical foundation that underpins all [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) results: **no-[arbitrage arguments](Forward%20Contracts%20and%20Forward%20Prices.md)** and **[risk-neutral pricing](Financial%20Mathematics%20Course.md)**. In an [arbitrage-free market](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md), every derivative’s price can be derived by assuming the existence of a [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md) $Q$ under which all asset prices (when discounted) are martingales. Formally, if $V(t)$ is the price process of any tradable asset, then $$\frac{V(t)}{B(t)} \text{ is a martingale under } Q, ;\text{i.e.}; \mathbb{E}^Q!\left[\frac{V(T)}{B(T)} \Big| \mathcal{F}_t\right] = \frac{V(t)}{B(t)}$$ for all $T \ge t$. This implies $\mathbb{E}^Q[V(T)] = V(t)\frac{B(T)}{B(t)}$, meaning the expected growth of $V$ is the [risk-free rate](Black%20Scholes%20Derivation.md). In particular, for any **[forward price](Forward%20Contracts%20and%20Forward%20Prices.md)** $F_t(T)$ (the price at time $t$ for future delivery at $T$), we must have $F_t(T) = \mathbb{E}^Q[S_T,|,\mathcal{F}_t]$ (because entering a forward requires no initial outlay, so its discounted value is a martingale). And since $\mathbb{E}^Q[S_T] = S_t e^{r(T-t)}$ under $Q$ when $r$ is constant, we get the classic [forward pricing formula](PSET%201-Financial%20Instruments.md) $F_t(T)=S_t e^{r(T-t)}$ . More generally, the _First [Fundamental Theorem](.md) of Asset Pricing_ guarantees that _no [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) $\iff$ existence of a risk-neutral measure_ , so we can confidently use risk-neutral [expectations](FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) for [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) as long as we rule out [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md).

**State Prices and DF:** Another useful viewpoint is via **state-price deflators** or **Arrow–Debreu prices**. Let $\pi(t,T)$ be the time-$t$ price of a security paying $1 if a specific state of the world at time $T$ occurs (and 0 otherwise). The collection of these prices (for all states) defines a **state-price density** (or stochastic discount factor) $\xi_T$ such that any payoff $X_T$ has price $V_0 = \mathbb{E}[\xi_T X_T]$. In a risk-neutral world, $\xi_T = e^{-rT} \frac{dQ}{dP}$, and $\mathbb{E}[\xi_T X_T]$ reduces to $e^{-rT}\mathbb{E}^Q[X_T]$. Thus [risk-neutral pricing](Financial%20Mathematics%20Course.md) is effectively a [change of measure](Change%20of%20Probability%20Measure.md) that embeds the [discount factor](Discount%20Factors.md). All methods – [replication](Forward%20and%20Futures%20Contracts.md), state prices, [risk-neutral expectation](Risk-Neutral%20Probabilities.md) – yield the same [no-arbitrage price](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) if applied correctly.

**[Pricing](Arbitrage%20Pricing%20of%20Derivatives.md) Algorithm ([Monte Carlo](Teaching%20Note%207-Exotic%20Options%20And%20Derivative%20Pricing%20By%20Monte%20Carlo%20Simulation.md)):** While analytical formulas will be derived for each instrument, it’s worth noting a general algorithm for [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) via simulation, to illustrate risk-neutral valuation in practice:
```
**Algorithm: Monte Carlo Risk-Neutral Pricing**
1. Simulate $M$ independent sample paths for the underlying risk factors under the risk-neutral measure $Q$ (e.g. simulate $S_T$ such that its drift = $r$).
2. For each simulation $i$, compute the payoff $X_T^{(i)}$ of the derivative at maturity $T$.
3. Take the average payoff across simulations: $\overline{X}_T = \frac{1}{M}\sum_{i=1}^M X_T^{(i)}$.
4. Discount this average at the risk-free rate: $V_0 \approx e^{-rT}\,\overline{X}_T$.
```
As $M \to \infty$, $V_0$ converges to the true [no-arbitrage price](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) $e^{-rT}\mathbb{E}^Q[X_T]$. This algorithm underscores that once we specify dynamics under $Q$, [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) is “just” an expectation – albeit one often computed via elegant math rather than brute force.

With these foundations in mind, we now proceed to analyze and derive [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) formulas for specific instruments, starting with forward and [futures contracts](Mathematics%20of%20the%20Financial%20Markets.md).

**Forward and [Futures Contracts](Mathematics%20of%20the%20Financial%20Markets.md)**

**Forward Contracts:** A **[forward contract](Forward%20Points%20in%20Currency.md)** is an agreement entered at time $t$ to buy or sell an [underlying asset](Risk%20Neutral%20Pricing%20of%20Options.md) for a fixed **[forward price](Forward%20Contracts%20and%20Forward%20Prices.md)** $F_t(T)$ at a specified future date $T$. For example, a gold forward might lock in the purchase of 1 oz. of gold at $F_0(T)$ dollars, with delivery in 3 months. Importantly, no money changes hands initially for a forward (ignoring any collateral), so the contract’s initial value is set to zero by no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md). We consider a forward from the perspective of the **long** side (buyer at maturity) unless stated otherwise.

**[Forward Price](Forward%20Contracts%20and%20Forward%20Prices.md) Derivation:** To find the [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md)-free [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) $F_0(T)$ at inception, we use a classic [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) argument under the assumption of constant [risk-free rate](Black%20Scholes%20Derivation.md) $r$ and no carrying costs or income on the asset. Let $S_0$ be the current spot price of the underlying. Consider two strategies starting at time 0 and ending at time $T$:
• **Strategy A (Synthetic Forward):** Borrow $S_0$ dollars at the [risk-free rate](Black%20Scholes%20Derivation.md) $r$ (so owe $S_0 e^{rT}$ at $T$) and buy one unit of the asset now for $S_0$. This results in owning the asset at $T$ with a net outflow at maturity of $S_0 e^{rT}$.
• **Strategy B (Forward):** Enter a [long forward](Forward%20Rates%20Agreement.md) contract to buy one unit at time $T$ for the [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) $F_0(T)$. No [cash flow](Preview%20of%20the%20Book.md) now, and pay $F_0(T)$ at $T$ to receive the asset.

At time $T$, both strategies yield the same asset. Strategy A’s net cost at $T$ is $S_0 e^{rT}$ (loan repayment), while Strategy B’s net cost is $F_0(T)$. For no [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md), these total costs must be equal – otherwise one could profit by choosing the cheaper strategy and [shorting](Short%20Selling.md) the more expensive one. Thus we require: $$F_0(T) = S_0 e^{rT},.$$ If $F_0(T)$ were higher, one could short the forward (lock in selling at $F_0$), and execute Strategy A (borrow and buy asset) to deliver into the forward, pocketing a riskless profit $F_0 - S_0 e^{rT}$ . If $F_0(T)$ were lower, one could do the opposite: short-sell the asset and invest the proceeds $S_0$ at $r$, and take a [long forward](Forward%20Rates%20Agreement.md) to buy back at $F_0(T)$, yielding [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) profit $S_0 e^{rT} - F_0$ at $T$ . In summary, **the [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) must equal the future value of the spot price** under no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) (when the asset has no income or storage cost).

More generally, if the [underlying asset](Risk%20Neutral%20Pricing%20of%20Options.md) provides cash flows or has [storage costs](Primary%20vs.%20Secondary%20Commodities.md), the [forward pricing formula](PSET%201-Financial%20Instruments.md) adjusts for the **cost of carry**. For instance, if the asset pays a [continuous dividend](Hedging%20Strategies%20with%20Forwards.md) yield $q$ (or foreign interest rate in the case of a [currency](Forwards%20and%20Futures%20Notes.md)), then the [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) is: $$F_0(T) = S_0 e^{(r - q)T},,$$ which subtracts the present value of dividends from the cost . If the asset yields a known cash income of present value $I$ over $[0,T]$, then $F_0(T) = (S_0 - I),e^{rT}$; whereas if there are known [storage costs](Primary%20vs.%20Secondary%20Commodities.md) with present value $U$, then $F_0(T) = (S_0 + U),e^{rT}$. All of these are derived by constructing [arbitrage strategies](Purpose%20and%20Structure%20of%20Financial%20Markets%201.md) that include the income or cost streams appropriately (treating dividends like a negative cost, and storage as a positive cost). As a special case, a **[forward rate](Forward%20Points%20in%20Currency.md) agreement (FRA)** – a [forward contract](Forward%20Points%20in%20Currency.md) on an interest rate – will have a [forward rate](Forward%20Points%20in%20Currency.md) determined by the difference between [borrowing and lending](Swaps%20Types.md) (we discuss FRAs implicitly when covering swaps, as a swap is essentially a string of FRAs).

**Forward Value During the Contract:** Once a forward is entered at the fair price $F_0(T)$, its **value** at inception is zero to both long and short. However, as the underlying price moves and time passes, the [forward contract](Forward%20Points%20in%20Currency.md) acquires a non-zero **mark-to-market value** (the amount one side would pay to exit the contract). Suppose at time $t$ (before maturity) the underlying spot is $S_t$ and the [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) for maturity $T$ (for a new contract) is now $F_t(T)$. Consider a [forward contract](Forward%20Points%20in%20Currency.md) struck at the original price $K=F_0(T)$. The **[forward contract](Forward%20Points%20in%20Currency.md) value** to the long at time $t$ is the difference between locking in purchase at $K$ and the current fair price $F_t(T)$, appropriately discounted. Specifically, the [long forward](Forward%20Rates%20Agreement.md)’s time-$t$ value $V_t^{(forward)}$ is:
$$V_t = S_t - K e^{-r(T-t)},,$$
assuming [continuous compounding](Interest%20Rate%20Quotations.md). This can be derived by recognizing that a forward can be replicated by holding the underlying ($+S_t$) and borrowing $K e^{-r(T-t)}$ (so that $K$ with interest will be paid at $T$) . The difference $S_t - K e^{-r(T-t)}$ is the net value. When $K = F_t(T)$ ([forward price](Forward%20Contracts%20and%20Forward%20Prices.md) is reset to fair), this value is zero (as expected). If $K$ is less than the current [fair forward price](Chapter%203%20-%20Forward%20and%20Futures%20Prices.md), the [long forward](Forward%20Rates%20Agreement.md) is “in the money” (positive value), since they locked in a cheaper purchase than the market forward; if $K$ is above market $F_t$, the forward has negative value to the long.

**Example:** If you entered a 6-month forward to buy a stock at $K=100$ and after 3 months the [stock price](Chapter%2016%20-%20Black–Scholes%20Model.md) is $S_{3m}=105$ with 3-month remaining [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) $F_{3m}(6m)=106$ (assuming some dividends or rates), then the value of your [forward contract](Forward%20Points%20in%20Currency.md) at 3 months is $105 - 100e^{-r(0.25)} \approx 105 - 100e^{-0.25r}$. If $r=0$, that’s simply $+5$ (you’d have a $5 gain, since you locked in at 100 while a new forward costs 105).

**[Futures Contracts](Mathematics%20of%20the%20Financial%20Markets.md):** A **[futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) contract** is similar to a forward in that it obligates the purchase or sale of an asset at a future date for a set price. However, [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) are exchange-traded, standardized, and **marked-to-market daily**. Mark-to-market means that gains and losses on a [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) position are settled in cash each day, and the [futures price](Futures%20Price%20and%20the%20Quality%20Option%20Before%20E.md) is reset to a new level until delivery. Despite these differences, if [interest rates](Interest%20Rate%20Quotations.md) are constant and there are no other frictions, the **[forward price](Forward%20Contracts%20and%20Forward%20Prices.md) equals the [futures price](Futures%20Price%20and%20the%20Quality%20Option%20Before%20E.md)** for the same maturity . Intuitively, with deterministic $r$, the interim cash flows from marking-to-market can be reinvested at the [risk-free rate](Black%20Scholes%20Derivation.md), leaving no difference in present value.

When [interest rates](Interest%20Rate%20Quotations.md) are **stochastic**, forward and [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) prices can diverge slightly. The [daily settlement](Pricing%20and%20Hedging%20Implications%20of%20Daily%20Sett.md) feature of [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) means that if [asset price](A%20Preview%20of%20Alternative%20Formulations.md) movements are positively correlated with [interest rate changes](How%20Countries%20Go%20Broke-Chapter%2012%20to%20Chapter%2014.md), a long [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) tends to earn gains when rates are high (which can be reinvested at a high rate) and losses when rates are low, making the [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) more attractive than a forward. Conversely, negative correlation makes [forwards](Forwards%20and%20Futures.md) slightly more valuable. In fact, **if $\text{Corr}(S_t, r_t) > 0$ then [futures price](Futures%20Price%20and%20the%20Quality%20Option%20Before%20E.md) $>$ [forward price](Forward%20Contracts%20and%20Forward%20Prices.md); if $\text{Corr} < 0$ then [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) $<$ forward** . These differences are second-order in many cases, and practitioners often assume forward $\approx$ [futures price](Futures%20Price%20and%20the%20Quality%20Option%20Before%20E.md) unless dealing with long-dated contracts or significant rate volatility. We will generally not distinguish between forward and [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) prices in the formulas below (taking that assumption, or using $F$ for both), unless noted.

**[Pricing](Arbitrage%20Pricing%20of%20Derivatives.md) via [Risk-Neutral Expectation](Risk-Neutral%20Probabilities.md):** The [forward pricing](Chapter%203%20-%20Forward%20and%20Futures%20Prices.md) result can be alternatively obtained by risk-neutral valuation. Under the [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md) $Q$, the **expected spot price** at time $T$ grows at rate $r$: $\mathbb{E}^Q[S_T]=S_0 e^{rT}$. Because a [forward contract](Forward%20Points%20in%20Currency.md) has zero initial cost, its [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) must satisfy $F_0(T) = \mathbb{E}^Q[S_T]$ (otherwise an [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) via long/[short forward](Forward%20Rates%20Agreement.md) vs. underlying would exist). Thus $F_0(T)=S_0 e^{rT}$, consistent with our [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) derivation. In fact, we can express the _time-$t$ forward price_ as $$F_t(T) = \frac{\mathbb{E}^Q[S_T,|,\mathcal{F}_t]}{\mathbb{E}^Q[B(T)/B(t),|,\mathcal{F}_t]} = \frac{\mathbb{E}^Q[S_T,|,\mathcal{F}_t]}{e^{r(T-t)}},$$ which again yields $S_t e^{r(T-t)}$ in the simple case. For [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md), because of [daily settlement](Pricing%20and%20Hedging%20Implications%20of%20Daily%20Sett.md), one shows $\displaystyle F^{\text{fut}}_t(T) = \mathbb{E}^Q[S_T,|,\mathcal{F}_t]$ (the expectation under $Q$ without discounting, since each day’s gains are realized immediately). If $r$ is constant, this equals the [forward price](Forward%20Contracts%20and%20Forward%20Prices.md) after accounting for discounting day by day, but if $r$ is random, $\mathbb{E}^Q[S_T] e^{-r(T-t)} \neq \mathbb{E}^Q[S_T]$ in general, hence forward $\neq$ [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) in that scenario.

**Summary ([Forwards](Forwards%20and%20Futures.md)/[Futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md)):** A [forward contract](Forward%20Points%20in%20Currency.md)’s no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) delivery **price** at inception is $F_t(T)=S_t e^{(r+c-q)(T-t)}$ (where $c$ is storage cost and $q$ yield). The **value** of an existing forward ([long position](Financial%20Engineering/Derivatives/Part%20I%20-%20Forwards%20and%20Futures/Chapter%204%20-%20Futures:%20Hedging%20and%20Speculation.md)) is $V_t = S_t e^{-q(T-t)} - K e^{-r(T-t)}$, which at $t=0$ reduces to $0$ when $K=F_0(T)$. [Futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) prices are generally equal to forward prices under the simple assumptions of constant [interest rates](Interest%20Rate%20Quotations.md) and no correlations. Both [forward and futures pricing](Part%20I-Basis%20Trading.md) illustrate that the expectation under the [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md) – adjusted for any cost-of-carry – determines the fair price. These instruments have linear payoffs and thus are easier to price; we now move to [fixed income instruments](Valuing%20Callable%20Bonds%20Using%20QuantLib%20Python.md) where [interest rates](Interest%20Rate%20Quotations.md) play a central role.

**Zero-Coupon Bonds and the [Term Structure](The%20Vasicek%20Model.md)**

A **zero-coupon bond** (or **discount bond**) maturing at date $T$ is the simplest fixed-income instrument: it pays a single unit of [currency](Forwards%20and%20Futures%20Notes.md) (e.g. $1) at $T$ and nothing before. Let $P(t,T)$ denote the time-$t$ price of this bond. By definition, $P(T,T)=1$ (at maturity it’s worth its face value). Absent default risk, a bond is essentially a risk-free asset if held to maturity. However, when interest rates are not constant, $P(t,T)$ will fluctuate as rates move – it’s a traded asset whose price reveals the **term structure of interest rates**. The _continuously-compounded yield_ $y(t,T)$ for maturity $T$ is defined via $P(t,T)=e^{-y(t,T),(T-t)}$. In particular, $y(0,T)$ is the **zero-coupon yield** for maturity $T$. The function $T \mapsto y(0,T)$ is the initial yield curve.

**No-[Arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) for Bonds:** Bonds with different maturities are linked by no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md): there should be no way to use short-term bonds to [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) long-term bonds and vice versa. In practice, an entire yield curve is fitted to market prices of bonds, Treasury bills, swaps, etc., to ensure consistency. A common procedure is **bootstrapping**: starting from the shortest maturities (where yields are directly observed) and solving for longer-term discount factors that match observed coupon bond prices. A **coupon bond** paying semiannual coupons, for example, can be seen as a [portfolio](An%20Asset%20Allocation%20Primer.md) of zero-coupon bonds (each coupon and principal is a [cash flow](Preview%20of%20the%20Book.md) at a known date). No-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) demands that the bond’s price equals the sum of the present values of each [cash flow](Preview%20of%20the%20Book.md) using the appropriate zero-coupon rates for each period. If not, an arbitrageur could strip the bond into zeros or reconstitute it to exploit mispricings. Thus, _coupon bond [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) requires a consistent set of discount factors $P(0,T_i)$ for all [cash flow](Preview%20of%20the%20Book.md) dates ${T_i}$_.

In a deterministic interest rate environment, $P(0,T)=e^{-rT}$ (with $r$ constant) or more generally $P(0,T)=e^{-\int_0^T r(u),du}$ for a time-varying rate $r(u)$. Under [stochastic interest rates](Appendix%205.C%20Forward%20And%20Futures%20Prices%20When%20Interest%20Rates%20Are%20Random.md), the price is given by a [risk-neutral expectation](Risk-Neutral%20Probabilities.md):
$$P(t,T) = \mathbb{E}^Q!\bigg[\exp!\Big(-\int_t^T r(s)ds\Big)\Big|,\mathcal{F}_t\bigg],,$$
which is the discounted expected value of $1. This formula comes from considering a money-market account as numeraire (the _Girsanov theorem_ can be applied to show bond prices are martingales under the appropriate measure). In practice, specific **short-rate models** (Vasicek, Cox–Ingersoll–Ross, etc.) or **forward rate models** (HJM) are used to model $P(t,T)$. But without delving into those, we will assume we know the term structure $P(0,T)$, or equivalently zero rates, as inputs.

**Forward Rates:** A useful derived quantity is the **[forward interest rate](Forward%20Rate.md)** for borrowing between $T_1$ and $T_2$ as seen today. Denoted $f(0;T_1,T_2)$, it is defined via the relation
$$P(0,T_1) = P(0,T_2),\exp!\big(-f(0;T_1,T_2),(T_2-T_1)\big),,$$
so that $f(0;T_1,T_2)$ is the rate that makes an [investment](An%20Asset%20Allocation%20Primer.md) from $0$ to $T_2$ equivalent to investing until $T_1$ then rolling into a loan from $T_1$ to $T_2$. Solving, $f(0;T_1,T_2) = \frac{\ln P(0,T_1) - \ln P(0,T_2)}{T_2 - T_1}$. If [interest rates](Interest%20Rate%20Quotations.md) are continuous, this is also related to the instantaneous **[forward rate](Forward%20Points%20in%20Currency.md)** $f(0,T)$ via $P(0,T)=\exp(-\int_0^T f(0,u),du)$. In a no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) setting, forward rates extracted from bond prices are consistent with forward contracts on [interest rates](Interest%20Rate%20Quotations.md) (FRAs). Indeed, the [no-arbitrage price](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) of a **[forward rate](Forward%20Points%20in%20Currency.md) agreement** that fixes the rate for $[T_1,T_2]$ at $K$ can be found by considering lending/borrowing strategies in bonds: one can show the present value of the payoff is $(f(0;T_1,T_2)-K),(T_2-T_1)P(0,T_2)$ (which is analogous to the [forward contract](Forward%20Points%20in%20Currency.md) value formula $S - K e^{-rT}$, with $S$ replaced by [forward rate](Forward%20Points%20in%20Currency.md) and discount by $P$). We won’t derive FRA [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) in detail, as it will be subsumed by the discussion of swaps.

**[Risk-Neutral Pricing](Financial%20Mathematics%20Course.md) for Bonds:** By treating the bond as the asset and the [money-market account](Appendix%205.C%20Forward%20And%20Futures%20Prices%20When%20Interest%20Rates%20Are%20Random.md) as numeraire, one can derive that _each $P(t,T)$ must equal the [risk-neutral expectation](Risk-Neutral%20Probabilities.md) of its payoff 1, discounted by $B(T)/B(t)$._ This yields the earlier expectation formula. It also implies that [trading strategies](Quantitative%20Trading%20Strategies%20Lecture%20Notes.md) involving bonds must satisfy no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md); for instance, a **rolling over strategy** of short-term bonds cannot outgun a long-term bond if the forward rates are set properly.

**Summary (Bonds):** Zero-coupon bond prices $P(0,T)$ encode the discount factors for [future cash flows](Advanced%20Derivatives%20Pricing%20Methodology.md) and determine the [term structure of interest rates](6.%20A%20Brief%20Introduction%20to%20Stochastic%20Calculus.md). [Arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) considerations enforce that coupon bond prices equal the sum of zero-coupon bond equivalents. Forward [interest rates](Interest%20Rate%20Quotations.md) are derived from zero prices and coincide with FRA rates under no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md). We now use these concepts as building blocks for [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) **interest rate swaps**, which are essentially exchanges of fixed and floating [cash flow streams](1.%20DeterministicCashFlows.md) and heavily depend on the [term structure](The%20Vasicek%20Model.md).

**Interest Rate Swaps**

An **[interest rate swap](Primer%20on%20Interest%20Rate%20Swaps.md)** is a derivative in which two parties [exchange cash flows](Fundamentals%20of%20Swaps.md) of two different types of interest payments on a [notional principal](Fundamentals%20of%20Swaps.md) amount. The most common type is a **plain vanilla [interest rate swap](Primer%20on%20Interest%20Rate%20Swaps.md)**: one party pays a [fixed interest rate](Chapter%2036%20-%20Currency%20Swaps.md) $R_{\text{fixed}}$ on the notional and receives a floating rate (such as LIBOR or SOFR) from the other party (who does the opposite). These payments occur periodically (e.g. semiannually) over a term of the swap. No principal is exchanged in a vanilla swap; only the net interest difference is paid each period. Swaps allow conversion between fixed-rate and floating-rate exposures and are fundamental in [interest rate risk](Analysis%20of%20Fixed%20Income%20Securities.md) management.

**Swap as Exchange of Bonds:** A useful way to conceptualize a [fixed-for-floating swap](Swaptions.md) is as the difference between two bond positions. Consider a **payer swap** (the party who pays fixed and receives floating): this position can be replicated by (i) **short** a fixed-rate bond (paying coupons $R_{\text{fixed}}$ and principal) and (ii) **long** a floating-rate note of the same notional and maturity. A floating-rate note (FRN) typically pays the benchmark rate (e.g. LIBOR) each period and is reset such that it always trades at par at coupon dates (assuming no [credit risk](Quantitative%20Trading%20Strategies%20Lecture%20Notes.md)). Thus, at coupon reset dates, the FRN’s value [returns](Assets.md) to the notional. If we assume the [floating leg](Pricing%20Interest%20Rate%20Swaps.md) is tied to a risk-free benchmark, the present value of receiving floating over each period plus getting back notional at end is just the notional amount (because one could just hold that cash risk-free). In fact, at swap initiation (time 0), the **present value of the [floating leg](Pricing%20Interest%20Rate%20Swaps.md)** (for the full swap term) equals the [notional principal](Fundamentals%20of%20Swaps.md) _by construction_ when using the current forward rates. Meanwhile, the present value of the [fixed leg](Pricing%20Interest%20Rate%20Swaps.md) is the present value of a fixed coupon bond paying $R_{\text{fixed}}$ per period plus principal. For the swap to have zero initial value (a **[par swap](Determining%20the%20Expression%20for%20the%20Fair%20Value%20of%20the%20Swap%20Spread.md)**), these two present values must be equal. Therefore, the fixed rate $R_{\text{fixed}}$ is chosen such that the _fixed leg PV = notional_ (since the [floating leg](Pricing%20Interest%20Rate%20Swaps.md) PV is notional). This unique rate is called the **swap [par rate](Pricing%20Interest%20Rate%20Swaps.md)** $S(0,T)$ for the swap’s maturity $T$.

**[Swap Pricing](Citi-Guide%20to%20Swaps.md) (at Initiation):** Suppose the swap pays fixed $R$ at times $T_1, T_2, \dots, T_N = T$ (with $T_0=0$) and floating payments of the prevailing [forward rate](Forward%20Points%20in%20Currency.md) for each period (so effectively the [floating leg](Pricing%20Interest%20Rate%20Swaps.md) will realize forward rates in expectation). Let $\Delta_i = T_i - T_{i-1}$ be year-fractions for each period. The present value of the [fixed leg](Pricing%20Interest%20Rate%20Swaps.md) (per notional $1) is:
$$PV_{\text{fixed}} = R \sum_{i=1}^N \Delta_i,P(0,T_i) + P(0,T_N),,$$
which is the [coupon payments](Financial%20Markets/Fixed%20Income%20Securities%20Tools%20for%20Today's%20Markets/Chapter%203/Realized%20Returns.md) plus the notional returned at $T_N$. (We include $P(0,T_N)$ as the PV of receiving $1 at maturity, if the swap is structured to exchange notional at the end – in a plain vanilla interest swap typically notional is not exchanged, but conceptually the floating leg’s final interest plus return to par can be viewed as receiving notional; equivalently, one of the $P(0,T_i)$ terms could be interpreted as including the principal.) The present value of the [floating leg](Pricing%20Interest%20Rate%20Swaps.md) is:
$$PV_{\text{float}} = P(0,T_0) - P(0,T_N) + \sum_{i=1}^N P(0,T_i) - P(0,T_{i}),,$$
which telescopes to $P(0,T_0) - P(0,T_N) = 1 - P(0,T_N)$ (since $P(0,T_0)=1$). In other words, $PV_{\text{float}} = 1 - P(0,T_N)$ for $1 notional (this result holds if the first floating payment is known or negligible; a more precise approach shows it equals the difference between par at start and discount factor to end, effectively the same). Setting $PV_{\text{fixed}} = PV_{\text{float}}$ for a par swap, we solve for $R$:
$$R,\sum_{i=1}^N \Delta_i P(0,T_i) + P(0,T_N) = 1 \implies R,\sum_{i=1}^N \Delta_i P(0,T_i) = 1 - P(0,T_N),. $$
Thus the **[par swap](Determining%20the%20Expression%20for%20the%20Fair%20Value%20of%20the%20Swap%20Spread.md) fixed rate** is
$$R^* = \frac{1 - P(0,T_N)}{\sum_{i=1}^N \Delta_i,P(0,T_i)},.$$
This $R$ is the_ **_swap rate_** _that makes the swap’s initial value zero_ _. Each $P(0,T_i)$ is readily obtained from the zero curve. For example, if $T_N=5$ years with semiannual payments, $R$ is such that the PV of five years of semiannual $R_{2}$ payments plus $P(0,5)$ equals 1. If yield curve is flat at, say, 3% continuously, then ${} R \approx 3\%$ as expected. If the yield curve is upward sloping, $R^*$ will be higher than the [short rate](An%20Overview%20of%20the%20Vasicek%20Short%20Rate%20Model.md) but lower than long-term rates, roughly an average.

**Swap Valuation (After Initiation):** Once a swap is in place, its value may become positive or negative to a party as rates change. The **value of a swap** at time $t$ (to the fixed-rate payer) can be computed as the difference between the present value of remaining floating payments and remaining fixed payments. Let $R_{\text{fixed}}$ be the original fixed rate on the swap, and let $R_{\text{new}}(t)$ be the current [par swap](Determining%20the%20Expression%20for%20the%20Fair%20Value%20of%20the%20Swap%20Spread.md) rate for the remaining term (i.e. the [swap rate](Teaching%20Note%204%20Interest%20Rate%20Derivatives.md) one would get on a new swap from $t$ to $T_N$). Then the **swap value** to the fixed payer (who pays $R_{\text{fixed}}$) at $t$ (per $1 notional) is:
$$V_t^{\text{payer}} = (R_{\text{new}}(t) - R_{\text{fixed}}),\sum_{i=k+1}^N \Delta_i P(t,T_i),,$$
where $T_k$ is the last payment date passed (so payments $k+1$ to $N$ remain) . Here $\sum_{i=k+1}^N \Delta_i P(t,T_i)$ is the **annuity factor** (present value of \$1 paid each period over remaining dates). If the payer locked in a higher rate than current ($R_{\text{fixed}} > R_{\text{new}}$), then this value is negative (the fixed payer is paying above-market, a disadvantage). If rates have risen ($R_{\text{fixed}} < R_{\text{new}}$), the payer swap gains value (positive $V_t$). Equivalently, one can compute the value for the fixed-rate **receiver** as $V_t^{\text{receiver}} = (R_{\text{fixed}} - R_{\text{new}}(t)) \sum \Delta_i P(t,T_i)$ – the opposite sign. This formula comes directly from considering a portfolio of bonds: after initiation, the fixed leg is like a bond with coupon $R_{\text{fixed}}$, and the floating leg is like a FRN that is worth par. So the swap’s value is like long a bond with coupon $R_{\text{new}}$ and short a bond with coupon $R_{\text{fixed}}$, scaled by notional. This results in $(R_{\text{new}} - R_{\text{fixed}})$ times the bond’s **duration-weighted PV**, which is exactly the annuity factor $\sum \Delta_i P(t,T_i)$ .

Another way: one can imagine terminating (or initiating an offsetting swap) at time $t$. To do so, one would pay/receive the net present value difference. Thus $V_t$ can be found by computing $PV_{\text{fixed,old}}(t) - PV_{\text{fixed,new}}(t)$ (for the same [floating leg](Pricing%20Interest%20Rate%20Swaps.md)), which yields the above result since $PV_{\text{fixed,new}}(t)$ would equal the [floating leg](Pricing%20Interest%20Rate%20Swaps.md)’s PV.

**Example:** Suppose two years ago you entered a 7-year swap to pay fixed 3% and receive 6-month LIBOR, on $100 million. Now 2 years have passed (5 years remaining). Using today’s discount factors, you find the annuity $\sum_{i=1}^{10} \Delta_i P(0,T_i) = 4.8161$ (for 10 semiannual periods left) . Also, the current 5-year swap rate is calculated as ${} R_{\text{new}} = (1 - P(0,5))/4.8161 = 1.59\%$ . Your swap’s value as fixed payer is $(0.0159 - 0.03) \times 4.8161 \times \$100\text{M} = -  6.79\text{M}$ . It’s negative because you are paying 3% which is high relative to the new 1.59% market rate – you’d have to pay $6.79MM to transfer your swap to someone else (i.e. to receive fixed at 3% when market is 1.59%, the counterparty would demand compensation). Conversely, the fixed-rate receiver has a +$6.79MM position.

**Risk-Neutral View:** Under a [no-arbitrage pricing](.md) measure, each forward LIBOR rate (the underlying for each floating payment) has an expectation equal to its forward value. A [par swap](Determining%20the%20Expression%20for%20the%20Fair%20Value%20of%20the%20Swap%20Spread.md) initially has zero value because the [fixed leg](Pricing%20Interest%20Rate%20Swaps.md)’s promised payments are set exactly equal to the sequence of implied forward floating payments. As time evolves, the realization of [interest rates](Interest%20Rate%20Quotations.md) will make the [fixed leg](Pricing%20Interest%20Rate%20Swaps.md) too high or too low relative to forward rates, creating value. One could price a swap by modeling the joint evolution of the [short rate](An%20Overview%20of%20the%20Vasicek%20Short%20Rate%20Model.md) or forward rates and taking [expectations](FORWARD%20RATES%20AND%20TERM%20STRUCTURE.md) of the net present value of payments, but the linearity of swap payoffs allows the simpler “deterministic PV” approach above. Indeed, a vanilla swap has _no optionality_, so its price is just the difference of two bond portfolios, and one can compute it by deterministic cashflow discounting with the current zero curve (no need for complex optionality modeling). This is why swaps are often used to infer the _risk-free zero curve itself_ from swap rates in the market.

**Summary (Swaps):** The [fixed leg](Pricing%20Interest%20Rate%20Swaps.md) of a swap is priced as an annuity whose rate is set such that its initial PV equals the notional (the [floating leg](Pricing%20Interest%20Rate%20Swaps.md)’s PV). The swap [par rate](Pricing%20Interest%20Rate%20Swaps.md) $S(0,T)$ is given by the ratio of “1 minus last [discount factor](Discount%20Factors.md)” to “sum of discount factors” . The mark-to-market value of a swap during its life is proportional to the difference between the original fixed rate and current [par rate](Pricing%20Interest%20Rate%20Swaps.md), times the remaining annuity factor . Swaps are thus very convenient to price given a yield curve, and they facilitate the market’s bootstrapping of that curve. Next, we turn to **swaptions** – options on swaps – which introduce optionality and require a further step of risk-neutral valuation (often using the [Black model](Black%20Models%20for%20Bond%20Price%20Options%20Capsfloors.md)).

**Swaptions (Swap Options)**

A **swaption** is an option granting the right, but not the obligation, to enter an [interest rate swap](Primer%20on%20Interest%20Rate%20Swaps.md) at a specified future date. There are two types: a **[payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md)** gives the right to _pay fixed, receive floating_ (i.e. become the fixed-rate payer in a swap), while a **receiver swaption** gives the right to _receive fixed, pay floating_. For example, a 5Y5Y [payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) is an option (exercisable in 5 years) to enter a 5-year swap as fixed payer. Swaptions are widely used to hedge or speculate on [future interest rate](Forward%20Rate.md) moves and to add optionality to swap-based products.

**Swaption Payoff:** Consider a [payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) expiring at time $T$ on a swap that would run from $T$ to $T_N$ (with coupon dates $T_{j}$, $j=1\dots N$, $T_0=T$). Let $K$ be the agreed fixed rate (swaption strike). At exercise (time $T$), if the swaption holder chooses to exercise and enter the swap as fixed payer, they will pay fixed $K$ and receive floating. The _market swap rate_ $S(T)$ for that $T$–$T_N$ swap ([par rate](Pricing%20Interest%20Rate%20Swaps.md) at $T$ for maturity $T_N$) will determine whether exercise is favorable. The **intrinsic value** of a [payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) at expiry is the present value of the difference between the swap at the market rate $S(T)$ and the swap at the strike $K$, floored at zero (since one wouldn’t exercise if it’s negative). In other words, the payoff is the **swap’s value to the payer** at $T$, clipped at zero:
$$\Pi_{payer}(T) = \Big( S(T) - K \Big)^+ \sum_{i=1}^N \Delta_i P(T, T_i),,$$
times the notional. Here $\sum_{i=1}^N \Delta_i P(T,T_i)$ is the **annuity factor at $T$** (present value at $T$ of $1 per period over the swap, essentially $= \sum_{i=1}^N \Delta_i e^{-r(T_i-T)}$ under deterministic rates). This factor converts a rate difference into a monetary value. If $S(T) > K$, the payer swaption is in the money (payer can enter a swap paying $K$ when market demands a higher rate $S(T)$, a favorable deal), and the payoff equals the PV of receiving $(S(T)-K)$ over each period. If $S(T)\le K$, payoff is zero (better not to enter the swap). A **receiver swaption** similarly has payoff $\Big(K - S(T)\Big)^+ \sum_{i=1}^N \Delta_i P(T,T_i)$ (nonzero when $K >$ current [swap rate](Teaching%20Note%204%20Interest%20Rate%20Derivatives.md), since receiver would then get above-market fixed rate).

**[Pricing](Arbitrage%20Pricing%20of%20Derivatives.md) Swaptions:** Swaptions are more complex to price because the payoff depends on the entire set of [interest rates](Interest%20Rate%20Quotations.md) at $T$ (through $S(T)$ or the collection of bond prices $P(T,T_i)$). A full treatment requires an [interest rate model](An%20Overview%20of%20the%20Vasicek%20Short%20Rate%20Model.md) (e.g. Black’s model, [Bachelier model](Continuous-Time%20Stochastic%20Processes.md), or a short-rate/forward-rate model like Hull–White, LIBOR market model, etc.). However, a common market approach is to use an analog of the Black–Scholes formula known as **Black’s 1976 model** for swaptions . Black’s model assumes the **[forward swap](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) rate** $S(t)$ for the underlying swap follows a lognormal process under its appropriate forward measure (with a certain volatility $\sigma$). Under these assumptions, the swaption price can be expressed in closed form, similar to a call option on a forward asset.

In Black’s formula for a **[payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md)**, the price at time 0 is given by:
$$V_0^{\text{payer swaption}} = A(0),\Big[,F_S \Phi(d_1);-;K,\Phi(d_2)\Big],,$$
where:
• $F_S$ is the **[forward swap](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) rate** (today’s [par rate](Pricing%20Interest%20Rate%20Swaps.md) for the swap starting at $T$), essentially $R^*$ for that swap starting in future;
• $A(0) = \sum_{i=1}^N \Delta_i P(0,T_i)$ is the **annuity factor** (present value of $1 per swap period, from 0);
• $\Phi$ is the standard normal CDF;
• $d_{1,2} = \frac{\ln(F_S/K) \pm \frac{1}{2}\sigma^2 T}{\sigma\sqrt{T}},$;
• $\sigma$ is the implied **[swaption volatility](Swaption%20Skew.md)** (assumed constant);
• $T$ is the swaption expiration.

This formula is directly analogous to Black–Scholes: $A(0)$ plays the role of a [discount factor](Discount%20Factors.md) and size scaling, $F_S$ is like a [forward price](Forward%20Contracts%20and%20Forward%20Prices.md), and $K$ the strike. In fact, it can be derived by noting the swaption payoff is $A(T)(S(T)-K)^+$ for payer, and treating $A(T)$ as approximately constant (or using the annuity as numeraire, which leads to $S(t)$ being martingale under the _swap measure_). Black’s 1976 paper originally presented the formula for options on [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) , but it’s applied to swaptions by analogous reasoning. If we account for discrete compounding conventions, a more precise formula is:
$$V_0^{\text{payer}} = \frac{1 - (1+F_S/m)^{-mN}}{F_S};e^{-rT}\big[F_S\Phi(d_1) - K\Phi(d_2)\big],,$$
where $m$ is payments per year (this factor $\frac{1-(1+F_S/m)^{-mN}}{F_S}$ is essentially $A(0)$ in another guise) . The receiver swaption price by [put-call parity](7.%20Black%20Scholes%20Model.md) is
$$V_0^{\text{receiver}} = A(0),\big[K\Phi(-d_2) - F_S \Phi(-d_1)\big],,$$
or simply the payer formula with $K$ and $F_S$ swapped in sign inside the $\Phi$ arguments.

**Modeling Considerations:** The [risk-neutral pricing](Financial%20Mathematics%20Course.md) of swaptions can also be done using _Jamshidian’s trick_ in one-factor models (decomposing a swaption into a [portfolio](An%20Asset%20Allocation%20Primer.md) of bond options), or [Monte Carlo](Teaching%20Note%207-Exotic%20Options%20And%20Derivative%20Pricing%20By%20Monte%20Carlo%20Simulation.md) under a LIBOR market model where each LIBOR [forward rate](Forward%20Points%20in%20Currency.md) is lognormal (the industry standard for consistent caplet and swaption volatilities). The Black swaption formula is widely used to quote swaption implied volatilities. It assumes lognormal [swap rate](Teaching%20Note%204%20Interest%20Rate%20Derivatives.md) distribution; in low-rate or negative-rate environments, sometimes a normal assumption ([Bachelier model](Continuous-Time%20Stochastic%20Processes.md)) is used instead.

**Cap/Floor Parity with Swaptions:** Interestingly, there is a connection between swaptions and [interest rate caps](Chapter%2038%20-%20T-Bond%20Option,%20Caps,%20Floors%20and%20Collar.md)/[floors](Caps%20and%20Floors.md) (described next) via parity relationships. A [payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) (right to pay fixed) can be shown to be equivalent to a [portfolio](An%20Asset%20Allocation%20Primer.md) of caplets (a cap) with the same strike, and a receiver swaption equals a [portfolio](An%20Asset%20Allocation%20Primer.md) of floorlets (a floor), under certain assumptions. Alternatively, one can say: **Cap – Floor = Swap**, which implies by [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) that **Cap price – Floor price = PV of fixed-floating difference** . Indeed, if you hold a cap and short a floor (same strike $K$), you will receive payments whenever LIBOR $- K$ is positive (from the cap) and pay when $K - \text{LIBOR}$ is positive (due to the short floor), which net replicates paying floating vs $K$. This is exactly a swap with fixed $K$. Thus, **Cap(K) – Floor(K) = PV(\text{receive floating – pay fixed $K$})**, which is the [par swap](Determining%20the%20Expression%20for%20the%20Fair%20Value%20of%20the%20Swap%20Spread.md) value if $K$ equals the [par rate](Pricing%20Interest%20Rate%20Swaps.md) (zero at inception) . If $K$ differs from par, the difference in cap and floor prices equals the market value of a payer swap with rate $K$. These relationships ensure consistency across the [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) of caps, [floors](Caps%20and%20Floors.md), and swaptions.

**Summary (Swaptions):** Swaptions add optionality to swaps, with payoffs contingent on future swap rates. They are commonly priced via the **Black-76 model**, treating the swap’s fixed rate as the underlying instrument . The [payer swaption](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) formula resembles a call option on the [forward swap](Chapter%2039%20-%20Swaptions,%20Forward%20Swaps,%20and%20MBS.md) rate, scaled by the annuity factor. While we provided Black’s formula (ubiquitous in practice), rigorous [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) can be done with [term structure models](Financial%20Mathematics%20Course.md) under the [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md). Swaption contracts allow [hedging](Key%20Rates%20O1s%20Durations%20and%20Hedging.md) of [interest rate volatility](Fixed%20Income%20Versus%20Equity%20Derivatives.md) and are closely related to [caps and floors](Interest%20Rate%20Derivatives-An%20Introduction%20to%20the%20%20Pricing%20of%20Caps%20and%20Floors.md), which we discuss next.

**[Caps and Floors](Interest%20Rate%20Derivatives-An%20Introduction%20to%20the%20%20Pricing%20of%20Caps%20and%20Floors.md) (Interest Rate Options)**

An **interest rate cap** is essentially a [portfolio](An%20Asset%20Allocation%20Primer.md) of call options on a [short-term interest rate](The%20Gauss%20Model.md), often designed to limit a borrower’s floating interest payments. Conversely, an **interest rate floor** is a [portfolio](An%20Asset%20Allocation%20Primer.md) of put options on a rate, limiting a lender’s minimum received rate. [Caps and floors](Interest%20Rate%20Derivatives-An%20Introduction%20to%20the%20%20Pricing%20of%20Caps%20and%20Floors.md) are quoted in terms of their strike rate $K$ (the cap rate or floor rate) and typically reference a LIBOR-like index over a schedule of reset dates.

**Cap Definition:** A cap provides payoff in each period the reference interest rate exceeds $K$. For example, consider a cap on 3-month LIBOR with quarterly reset dates $T_1, T_2, \dots, T_N$. At each reset $T_i$ (when the new LIBOR $L_{i-1}(=L(T_{i-1},T_i))$ for $[T_{i-1},T_i]$ is determined), the cap will, at the next payment date $T_i$, pay the excess interest: $(L_{i-1} - K)^+ \Delta_i \cdot \text{Notional}$, where $\Delta_i$ is the [day-count](Intra-Year%20Compounding%20and%20Day-Count.md) fraction for that period . In other words, if LIBOR ends up higher than $K$, the caplet pays the difference * times the period length and notional (the additional interest cost). If LIBOR $\le K$, the caplet pays zero (the borrower’s rate is at or below the cap). The collection of these call-option-like payoffs for $i=1$ to $N$ constitutes the cap. Each individual option is called a **caplet**.

**Floor Definition:** Similarly, a floor pays $(K - L_{i-1})^+ \Delta_i$ on each period $i$ – paying out when LIBOR falls below $K$, thus guaranteeing a minimum rate $K$ to the investor. Each piece is a **floorlet** (put option on the rate).

**Caplet [Pricing](Arbitrage%20Pricing%20of%20Derivatives.md):** Each caplet is effectively a European call option on the interest rate $L_{i-1}$ set at time $T_{i-1}$ for payment at $T_i$. To price a caplet, one usually uses a **forward measure**: for caplet on $L(T_{i-1},T_i)$, it is convenient to use the $T_i$-forward measure (with numeraire $P(t,T_i)$). Under this measure, the forward LIBOR for that period, $F_{i-1}(t) \approx L(t;T_{i-1},T_i)$, behaves like a martingale. Black’s model assumes $L_{i-1}$ (or equivalently $F_{i-1}$) is lognormal under this forward measure with volatility $\sigma_i$. Then the **Black formula for a caplet** (at time 0) is:
$$V_0^{\text{caplet}} = P(0,T_i),\Delta_i,\big[,F_{i-1}(0)\Phi(d_1) - K\Phi(d_2),\big],,$$
where $F_{i-1}(0)$ is the current [forward rate](Forward%20Points%20in%20Currency.md) for $[T_{i-1},T_i]$, and
$d_{1,2} = \frac{\ln(F_{i-1}(0)/K) \pm \frac{1}{2}\sigma_i^2 T_{i-1}}{\sigma_i \sqrt{T_{i-1}}},$ (assuming caplet decision is effectively at $T_{i-1}$). We also multiplied by $\Delta_i$ because the payoff is $(L-K)\Delta_i$ . This formula is directly analogous to an option on a [forward rate](Forward%20Points%20in%20Currency.md) agreement. The factor $P(0,T_i)$ is the discount to the payment date. In practice, market quotes cap implied volatilities for different maturities and strikes, and uses Black’s formula to price each caplet accordingly (with interpolation for intermediate).

A key point: Because each caplet payoff occurs at $T_i$ but is determined by $L$ fixed at $T_{i-1}$, using $T_i$ as numeraire simplifies the payoff to something like $\frac{1}{1+L\Delta}$ times a simple difference . The standard Black formula accounts for the required [convexity adjustment](Financial%20Engineering/Derivatives/Part%20II%20-%20Fixed%20Income%20Cash%20Markets/Chapter%2010%20-%20Bonds:%20Duration%20and%20Convexity.md) via the $\Delta_i$ factor and discounting.

**Cap = Sum of Caplets:** The total cap price is the sum of the present values of all its caplets:
$$V_0^{\text{cap}} = \sum_{i=1}^N V_0^{\text{caplet, }i}, = \sum_{i=1}^{N} P(0,T_i),\Delta_i,\big[F_{i-1}(0)\Phi(d_{1,i}) - K\Phi(d_{2,i})\big],,$$
with appropriate $d_{1,i}, d_{2,i}$ for each caplet expiring $T_{i-1}$ . Similarly a floor price is the sum of floorlets:
$$V_0^{\text{floor}} = \sum_{i=1}^{N} P(0,T_i),\Delta_i,\big[K\Phi(-d_{2,i}) - F_{i-1}(0)\Phi(-d_{1,i})\big],.$$
The decomposition into caplets/floorlets is possible because LIBOR resets for different periods are independent under their respective forward measures (in a one-factor setting), and because the payoff is linear in these separate pieces. In multi-factor models, one must be careful, but by definition of a cap as a series of individual options, this additivity holds for [pricing](Arbitrage%20Pricing%20of%20Derivatives.md).

**Cap-Floor Parity:** As mentioned earlier, a long cap and long floor with the same strike $K$ on the same dates replicate a fixed rate guarantee: cap pays when rates above $K$, floor pays when below, so together they ensure you effectively always either receive or pay adjustments to achieve rate $K$. In fact, **Long Cap + Long Floor = [Interest Rate Collar](Chapter%2038%20-%20T-Bond%20Option,%20Caps,%20Floors%20and%20Collar.md)** that locks the rate at $K$. The cost of this collar equals the cost of a swap that would pay fixed $K$ (because achieving exactly $K$ payments is a fixed-rate bond). Thus, $V_0^{\text{cap}}(K) - V_0^{\text{floor}}(K) = V_0^{\text{payer swap}}(K)$ (the value of paying fixed $K$ vs floating) . If $K$ is set to the current swap [par rate](Pricing%20Interest%20Rate%20Swaps.md), $V_0^{\text{payer swap}}(K)=0$, so the cap and floor have the same price. This is an important consistency check in interest rate models.

**Use Cases:** A cap can protect a borrower with a floating-rate loan by capping the maximum interest rate they pay (beyond which the cap payouts compensate the extra interest). A floor can ensure a minimum interest income for a lender on a floating-rate [investment](An%20Asset%20Allocation%20Primer.md). [Caps and floors](Interest%20Rate%20Derivatives-An%20Introduction%20to%20the%20%20Pricing%20of%20Caps%20and%20Floors.md) are often structured with notional amortization schedules to match specific loan principals. They trade actively in the [derivatives](Chapter%209%20Arbitrage%20and%20Hedging%20With%20Options.md) market (e.g. caps on 3M LIBOR for various maturities), and their implied volatilities form the **[volatility surface](7.%20Black%20Scholes%20Model.md)/skew** for [interest rates](Interest%20Rate%20Quotations.md).

**Summary ([Caps/Floors](Black%20Models%20for%20Bond%20Price%20Options%20Capsfloors.md)):** An interest rate cap is equivalent to a series of European call options on the interest rate for each period (caplets), and a floor is analogous with put options. Under no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md), the cap’s price is the sum of caplet prices, often computed with Black’s 1976 model . The [Black model](Black%20Models%20for%20Bond%20Price%20Options%20Capsfloors.md) formulas for caplets are akin to Black–Scholes, with forward LIBOR as underlying and discount bond as numeraire. Caps, [floors](Caps%20and%20Floors.md), and swaps satisfy parity relationships (cap – floor = swap) that must hold to avoid [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md). These instruments allow market participants to trade and hedge [interest rate volatility](Fixed%20Income%20Versus%20Equity%20Derivatives.md) and to tailor risk profiles (e.g. a collar strategy, which is long a cap and short a floor, can set an interest rate band).

**Conclusion and Further Reading**

In these notes, we’ve systematically derived the [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) of various [financial instruments](A%20Practical%20Guide%20for%20Actuaries%20and%20other%20Business%20Professionals..md) – [forwards](Forwards%20and%20Futures.md), [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md), bonds, swaps, swaptions, caps, and [floors](Caps%20and%20Floors.md) – using the twin principles of no [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) and risk-neutral valuation. We started from the foundation that in an [arbitrage-free market](Financial%20Markets/Financial%20Asset%20Pricing%20Theory%20Overview/Chapter%2012%20-%20Derivatives/Exercises.md) there exists a [risk-neutral measure](Verifying%20Martingale%20Property%20with%20Q.md) enabling simple expected-value [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) of discounted payoffs . We applied this to determine forward and [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) prices, seeing that forward prices are essentially expected future [spot prices](Contango%20And%20Backwardation%20In%20Arbitrage-Free%20Futures-Markets.md) grossed-up at the [risk-free rate](Black%20Scholes%20Derivation.md). We then covered bond [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) and the [term structure](The%20Vasicek%20Model.md), emphasizing how discount factors ensure consistency across maturities. Building on that, we priced interest rate swaps by equating fixed and floating-leg present values , and showed how a swap’s value evolves with changes in the [swap rate](Teaching%20Note%204%20Interest%20Rate%20Derivatives.md) . Swaptions introduced optionality on swaps, and we presented Black’s formula as a convenient closed-form solution . Finally, we detailed [caps and floors](Interest%20Rate%20Derivatives-An%20Introduction%20to%20the%20%20Pricing%20of%20Caps%20and%20Floors.md), breaking them into caplets/floorlets and again leveraging Black’s model for tractable [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) . Throughout, we highlighted [arbitrage strategies](Purpose%20and%20Structure%20of%20Financial%20Markets%201.md) and intuitive reasoning (e.g. constructing replicating portfolios or using parity relations) to reinforce why the [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) formulas take the form they do.

For further study, the following resources are recommended:
• **John C. Hull – Options, [Futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md), and Other [Derivatives](Chapter%209%20Arbitrage%20and%20Hedging%20With%20Options.md)** (often updated, e.g. 10th edition, 2017): A comprehensive text covering [derivatives pricing](Mathematics%20of%20the%20Financial%20Markets.md) with an intuitive approach. Hull’s chapters on swaps, [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md), and options provide concrete examples and additional context (e.g. [day-count conventions](Day-Count%20Conventions.md), collateral, etc.) beyond the idealized formulas.
• **Steven Shreve – [Stochastic Calculus](6.%20A%20Brief%20Introduction%20to%20Stochastic%20Calculus.md) for Finance II: [Continuous-Time Models](Financial%20Mathematics%20Course.md) (2004)**: This graduate-level text rigorously develops the [risk-neutral pricing](Financial%20Mathematics%20Course.md) framework with [Brownian motion](Continuous-Time%20Stochastic%20Processes.md) and martingales. It is an excellent reference for the theoretical foundations (including the Black–Scholes derivation, Girsanov’s theorem, and the fundamental theorems of [asset pricing](Fixed%20Income%20Asset%20Pricing.md)) that underlie the methods used in these notes.
• **Darrell Duffie – Dynamic [Asset Pricing Theory](Mean-Variance%20Efficient%20Returns%20and%20Pricing%20Fac.md) (3rd ed., 2001)**: A more abstract and advanced treatment of [arbitrage pricing](Risk-Neutral%20Pricing.md) in a general state-space setting. Duffie’s text is ideal for those interested in measure-theoretic foundations and the most general statements of the [no-arbitrage pricing](.md) theorems, as well as advanced topics like [incomplete markets](Lecture%20Notes%20on%20International%20Finance.md).
• **Fischer Black and Myron Scholes (1973), “The [Pricing](Arbitrage%20Pricing%20of%20Derivatives.md) of Options and Corporate Liabilities,” Journal of Political Economy**: The seminal paper introducing the Black–Scholes formula, which underpins much of risk-neutral option [pricing](Arbitrage%20Pricing%20of%20Derivatives.md). While focused on equity options, the methodology is foundational for understanding how no-[arbitrage arguments](Forward%20Contracts%20and%20Forward%20Prices.md) can lead to partial differential equations and [closed-form solutions](Financial%20Engineering/Derivatives/Part%20IX%20-%20Fixed%20Income%20Derivatives/Chapter%2040%20-%20Pricing%20Fixed%20Income%20Options:%20Black’s%20Model%20and%20MCS.md).
• **Fischer Black (1976), “The [Pricing](Arbitrage%20Pricing%20of%20Derivatives.md) of Commodity Contracts,” Journal of Financial Economics**: Black’s paper extends Black–Scholes to options on [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md), which became the basis for [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) caps, [floors](Caps%20and%20Floors.md), and swaptions (Black–76 model). It’s a short but insightful read to see how the formula we used for swaptions and caplets was originally derived for [futures](Futures%20Not%20Subject%20to%20Cash-And-Carry.md) options.
• **Damiano Brigo and Fabio Mercurio – Interest Rate Models: Theory and Practice (2nd ed., 2006)**: A thorough text specifically on interest rate [derivatives](Chapter%209%20Arbitrage%20and%20Hedging%20With%20Options.md). It covers the [pricing](Arbitrage%20Pricing%20of%20Derivatives.md) of caps, [floors](Caps%20and%20Floors.md), and swaptions in depth, examining the [Black model](Black%20Models%20for%20Bond%20Price%20Options%20Capsfloors.md) as well as more sophisticated models (Hull–White, LIBOR Market Model, etc.) for [interest rates](Interest%20Rate%20Quotations.md). This is excellent for understanding the limitations of Black’s model and how one calibrates to cap/floor volatilities and swaption volatilities in practice.
• **Leif B. G. Andersen and Vladimir Piterbarg – [Interest Rate Modeling](Arbitrage-Free%20Interest%20Rate%20Models.md) (3-volume set, 2010)**: An advanced and encyclopedic resource on interest rate models, including detailed discussions on [swaption pricing](Swaptions.md), [model calibration](Arbitrage-Free%20Interest%20Rate%20Models.md), and the mathematics of no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md) [term structure models](Financial%20Mathematics%20Course.md). Volume I lays the foundations and vanilla models, while Volume III goes into products and [risk management](Financial%20Mathematics%20Course.md).
• **Harrison & Kreps (1979) and Harrison & Pliska (1981)**: These papers formally develop the concept of equivalent [martingale measures](Financial%20Mathematics%20Course.md) and [risk-neutral pricing](Financial%20Mathematics%20Course.md) in both discrete and continuous time. They are the classic references for the fundamental theorems of [asset pricing](Fixed%20Income%20Asset%20Pricing.md) in academic finance.

By consulting these materials, one can deepen their understanding of both the practical formulas and the theoretical mechanisms behind them. Each of the instruments discussed has further nuances ([credit risk](Quantitative%20Trading%20Strategies%20Lecture%20Notes.md), collateralization, multi-curves for different interest rate benchmarks, etc.) which become important in real-world contexts. However, the no-[arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md), [risk-neutral pricing](Financial%20Mathematics%20Course.md) paradigm remains the unifying theme that ensures different market prices all fit into a coherent, [arbitrage](Arbitrage%20Pricing%20of%20Derivatives.md)-free framework.